In [1]:
# Path para diret√≥rio raiz do projeto
import sys
sys.path.insert(0, sys.path[0].removesuffix("/src/jupyter"))

import pandas as pd
import src.utils as utils

In [2]:
data_file_list = utils.get_data_files()

for data_file in data_file_list:
	data = pd.read_csv(data_file, sep=';')
	if data.shape[0] > 0:
		data = utils.calc_ema_periods(data, periods_of_time=[200], close_price='adj_close', diff_price=True)
		data = utils.calc_ema_periods(data, periods_of_time=[200], close_price='close', diff_price=True)
		data = utils.calc_RSI(data, close_price='adj_close')
		#data.dropna(inplace=True)
		data = data.round(2)
		data.to_csv(data_file, sep=';', index=False)
		print(f'Ticker: {data.tail(1).ticker.values[0]} - Shape {data.shape}')
		data.info()

Ticker: POMO4.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: RZAK11.SA - Shape (728, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 728 entries, 0 to 727
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              728 non-null    object
 1   open_time                728 non-null    int64
 2   ticker                   728 non-null    object
 3   open                     728 non-null    float64
 4   high                     728 non-null    float64
 5   low                      728 non-null    float64
 6   close                    728 non-null    float64
 7   adj_close                728 non-null    float64
 8   volume                   728 non-null    int64
 9   type                     728 non-null    object
 10  ema_adj_close_200p       529 non-null    float32
 11  ema_adj_close_200p_diff  529 non-null    float32
 12  ema_close_200p           529 non-null    float32
 13  ema_close_200p_diff      529 non-null    float32
 14  rsi                      714 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 74.1+ KB
Ticker: NGRD3.SA - Shape (732, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              732 non-null    object
 1   open_time                732 non-null    int64
 2   ticker                   732 non-null    object
 3   open                     732 non-null    float64
 4   high                     732 non-null    float64
 5   low                      732 non-null    float64
 6   close                    732 non-null    float64
 7   adj_close                732 non-null    float64
 8   volume                   732 non-null    int64
 9   type                     732 non-null    object
 10  ema_adj_close_200p       533 non-null    float32
 11  ema_adj_close_200p_diff  533 non-null    float32
 12  ema_close_200p           533 non-null    float32
 13  ema_close_200p_diff      533 non-null    float32
 14  rsi                      718 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 74.5+ KB
Ticker: BSLI3.SA - Shape (5615, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5615 entries, 0 to 5614
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5615 non-null   object
 1   open_time                5615 non-null   int64
 2   ticker                   5615 non-null   object
 3   open                     5615 non-null   float64
 4   high                     5615 non-null   float64
 5   low                      5615 non-null   float64
 6   close                    5615 non-null   float64
 7   adj_close                5615 non-null   float64
 8   volume                   5615 non-null   int64
 9   type                     5615 non-null   object
 10  ema_adj_close_200p       5416 non-null   float32
 11  ema_adj_close_200p_diff  5416 non-null   float32
 12  ema_close_200p           5416 non-null   float32
 13  ema_close_200p_diff      5416 non-null   float32
 14  rsi                      3685 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 570.4+ KB
Ticker: TRAD3.SA - Shape (586, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 586 entries, 0 to 585
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              586 non-null    object
 1   open_time                586 non-null    int64
 2   ticker                   586 non-null    object
 3   open                     586 non-null    float64
 4   high                     586 non-null    float64
 5   low                      586 non-null    float64
 6   close                    586 non-null    float64
 7   adj_close                586 non-null    float64
 8   volume                   586 non-null    int64
 9   type                     586 non-null    object
 10  ema_adj_close_200p       387 non-null    float32
 11  ema_adj_close_200p_diff  387 non-null    float32
 12  ema_close_200p           387 non-null    float32
 13  ema_close_200p_diff      387 non-null    float32
 14  rsi                      572 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 59.6+ KB
Ticker: LPSB3.SA - Shape (4204, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4204 entries, 0 to 4203
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4204 non-null   object
 1   open_time                4204 non-null   int64
 2   ticker                   4204 non-null   object
 3   open                     4204 non-null   float64
 4   high                     4204 non-null   float64
 5   low                      4204 non-null   float64
 6   close                    4204 non-null   float64
 7   adj_close                4204 non-null   float64
 8   volume                   4204 non-null   int64
 9   type                     4204 non-null   object
 10  ema_adj_close_200p       4005 non-null   float32
 11  ema_adj_close_200p_diff  4005 non-null   float32
 12  ema_close_200p           4005 non-null   float32
 13  ema_close_200p_diff      4005 non-null   float32
 14  rsi                      4190 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 427.1+ KB
Ticker: ALPA3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
index 14 is out of bounds for axis 0 with size 1
Ticker: SOLR11.SA - Shape (1, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1 non-null      object
 1   open_time                1 non-null      int64
 2   ticker                   1 non-null      object
 3   open                     1 non-null      float64
 4   high                     1 non-null      float64
 5   low                      1 non-null      float64
 6   close                    1 non-null      float64
 7   adj_close                1 non-null      float64
 8   volume                   1 non-null      int64
 9   type                     1 non-null      object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
dtypes: float64(5), int64(2), object(7)
memory usage: 244.0+ bytes
Ticker: GAME11.SA - Shape (473, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 473 entries, 0 to 472
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              473 non-null    object
 1   open_time                473 non-null    int64
 2   ticker                   473 non-null    object
 3   open                     473 non-null    float64
 4   high                     473 non-null    float64
 5   low                      473 non-null    float64
 6   close                    473 non-null    float64
 7   adj_close                473 non-null    float64
 8   volume                   473 non-null    int64
 9   type                     473 non-null    object
 10  ema_adj_close_200p       274 non-null    float32
 11  ema_adj_close_200p_diff  274 non-null    float32
 12  ema_close_200p           274 non-null    float32
 13  ema_close_200p_diff      274 non-null    float32
 14  rsi                      459 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 48.2+ KB
Ticker: EALT4.SA - Shape (5982, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5982 entries, 0 to 5981
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5982 non-null   object
 1   open_time                5982 non-null   int64
 2   ticker                   5982 non-null   object
 3   open                     5982 non-null   float64
 4   high                     5982 non-null   float64
 5   low                      5982 non-null   float64
 6   close                    5982 non-null   float64
 7   adj_close                5982 non-null   float64
 8   volume                   5982 non-null   int64
 9   type                     5982 non-null   object
 10  ema_adj_close_200p       5783 non-null   float32
 11  ema_adj_close_200p_diff  5783 non-null   float32
 12  ema_close_200p           5783 non-null   float32
 13  ema_close_200p_diff      5783 non-null   float32
 14  rsi                      5030 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 607.7+ KB
Ticker: POMO3.SA - Shape (6000, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6000 non-null   object
 1   open_time                6000 non-null   int64
 2   ticker                   6000 non-null   object
 3   open                     6000 non-null   float64
 4   high                     6000 non-null   float64
 5   low                      6000 non-null   float64
 6   close                    6000 non-null   float64
 7   adj_close                6000 non-null   float64
 8   volume                   6000 non-null   int64
 9   type                     6000 non-null   object
 10  ema_adj_close_200p       5801 non-null   float32
 11  ema_adj_close_200p_diff  5801 non-null   float32
 12  ema_close_200p           5801 non-null   float32
 13  ema_close_200p_diff      5801 non-null   float32
 14  rsi                      5971 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.5+ KB

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: SLED3.SA - Shape (6006, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6006 entries, 0 to 6005
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6006 non-null   object
 1   open_time                6006 non-null   int64
 2   ticker                   6006 non-null   object
 3   open                     6006 non-null   float64
 4   high                     6006 non-null   float64
 5   low                      6006 non-null   float64
 6   close                    6006 non-null   float64
 7   adj_close                6006 non-null   float64
 8   volume                   6006 non-null   int64
 9   type                     6006 non-null   object
 10  ema_adj_close_200p       5807 non-null   float32
 11  ema_adj_close_200p_diff  5807 non-null   float32
 12  ema_close_200p           5807 non-null   float32
 13  ema_close_200p_diff      5807 non-null   float32
 14  rsi                      5992 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.1+ KB
Ticker: PLAS3.SA - Shape (6005, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6005 entries, 0 to 6004
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6005 non-null   object
 1   open_time                6005 non-null   int64
 2   ticker                   6005 non-null   object
 3   open                     6005 non-null   float64
 4   high                     6005 non-null   float64
 5   low                      6005 non-null   float64
 6   close                    6005 non-null   float64
 7   adj_close                6005 non-null   float64
 8   volume                   6005 non-null   int64
 9   type                     6005 non-null   object
 10  ema_adj_close_200p       5806 non-null   float32
 11  ema_adj_close_200p_diff  5806 non-null   float32
 12  ema_close_200p           5806 non-null   float32
 13  ema_close_200p_diff      5806 non-null   float32
 14  rsi                      5991 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.0+ KB
Ticker: VALE3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: VGIP11.SA - Shape (920, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              920 non-null    object
 1   open_time                920 non-null    int64
 2   ticker                   920 non-null    object
 3   open                     920 non-null    float64
 4   high                     920 non-null    float64
 5   low                      920 non-null    float64
 6   close                    920 non-null    float64
 7   adj_close                920 non-null    float64
 8   volume                   920 non-null    int64
 9   type                     920 non-null    object
 10  ema_adj_close_200p       721 non-null    float32
 11  ema_adj_close_200p_diff  721 non-null    float32
 12  ema_close_200p           721 non-null    float32
 13  ema_close_200p_diff      721 non-null    float32
 14  rsi                      906 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 93.6+ KB
Ticker: LAND3.SA - Shape (577, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              577 non-null    object
 1   open_time                577 non-null    int64
 2   ticker                   577 non-null    object
 3   open                     577 non-null    float64
 4   high                     577 non-null    float64
 5   low                      577 non-null    float64
 6   close                    577 non-null    float64
 7   adj_close                577 non-null    float64
 8   volume                   577 non-null    int64
 9   type                     577 non-null    object
 10  ema_adj_close_200p       378 non-null    float32
 11  ema_adj_close_200p_diff  378 non-null    float32
 12  ema_close_200p           378 non-null    float32
 13  ema_close_200p_diff      378 non-null    float32
 14  rsi                      563 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 58.7+ KB
Ticker: BIOM3.SA - Shape (6001, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6001 entries, 0 to 6000
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6001 non-null   object
 1   open_time                6001 non-null   int64
 2   ticker                   6001 non-null   object
 3   open                     6001 non-null   float64
 4   high                     6001 non-null   float64
 5   low                      6001 non-null   float64
 6   close                    6001 non-null   float64
 7   adj_close                6001 non-null   float64
 8   volume                   6001 non-null   int64
 9   type                     6001 non-null   object
 10  ema_adj_close_200p       5802 non-null   float32
 11  ema_adj_close_200p_diff  5802 non-null   float32
 12  ema_close_200p           5802 non-null   float32
 13  ema_close_200p_diff      5802 non-null   float32
 14  rsi                      5987 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.6+ KB
Ticker: BMEB3.SA - Shape (5866, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5866 entries, 0 to 5865
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5866 non-null   object
 1   open_time                5866 non-null   int64
 2   ticker                   5866 non-null   object
 3   open                     5866 non-null   float64
 4   high                     5866 non-null   float64
 5   low                      5866 non-null   float64
 6   close                    5866 non-null   float64
 7   adj_close                5866 non-null   float64
 8   volume                   5866 non-null   int64
 9   type                     5866 non-null   object
 10  ema_adj_close_200p       5667 non-null   float32
 11  ema_adj_close_200p_diff  5667 non-null   float32
 12  ema_close_200p           5667 non-null   float32
 13  ema_close_200p_diff      5667 non-null   float32
 14  rsi                      5852 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 595.9+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: FGAA11.SA - Shape (198, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              198 non-null    object
 1   open_time                198 non-null    int64
 2   ticker                   198 non-null    object
 3   open                     198 non-null    float64
 4   high                     198 non-null    float64
 5   low                      198 non-null    float64
 6   close                    198 non-null    float64
 7   adj_close                198 non-null    float64
 8   volume                   198 non-null    int64
 9   type                     198 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      184 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 23.3+ KB
Ticker: BTCR11.SA - Shape (1218, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1218 non-null   object
 1   open_time                1218 non-null   int64
 2   ticker                   1218 non-null   object
 3   open                     1218 non-null   float64
 4   high                     1218 non-null   float64
 5   low                      1218 non-null   float64
 6   close                    1218 non-null   float64
 7   adj_close                1218 non-null   float64
 8   volume                   1218 non-null   int64
 9   type                     1218 non-null   object
 10  ema_adj_close_200p       1019 non-null   float32
 11  ema_adj_close_200p_diff  1019 non-null   float32
 12  ema_close_200p           1019 non-null   float32
 13  ema_close_200p_diff      1019 non-null   float32
 14  rsi                      1187 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 123.8+ KB
Ticker: BPFF11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: USIM3.SA - Shape (6006, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6006 entries, 0 to 6005
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6006 non-null   object
 1   open_time                6006 non-null   int64
 2   ticker                   6006 non-null   object
 3   open                     6006 non-null   float64
 4   high                     6006 non-null   float64
 5   low                      6006 non-null   float64
 6   close                    6006 non-null   float64
 7   adj_close                6006 non-null   float64
 8   volume                   6006 non-null   int64
 9   type                     6006 non-null   object
 10  ema_adj_close_200p       5807 non-null   float32
 11  ema_adj_close_200p_diff  5807 non-null   float32
 12  ema_close_200p           5807 non-null   float32
 13  ema_close_200p_diff      5807 non-null   float32
 14  rsi                      5992 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.1+ KB
Ticker: TRXF11.SA - Shape (941, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              941 non-null    object
 1   open_time                941 non-null    int64
 2   ticker                   941 non-null    object
 3   open                     941 non-null    float64
 4   high                     941 non-null    float64
 5   low                      941 non-null    float64
 6   close                    941 non-null    float64
 7   adj_close                941 non-null    float64
 8   volume                   941 non-null    int64
 9   type                     941 non-null    object
 10  ema_adj_close_200p       742 non-null    float32
 11  ema_adj_close_200p_diff  742 non-null    float32
 12  ema_close_200p           742 non-null    float32
 13  ema_close_200p_diff      742 non-null    float32
 14  rsi                      927 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.7+ KB
Ticker: JPPA11.SA - Shape (941, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              941 non-null    object
 1   open_time                941 non-null    int64
 2   ticker                   941 non-null    object
 3   open                     941 non-null    float64
 4   high                     941 non-null    float64
 5   low                      941 non-null    float64
 6   close                    941 non-null    float64
 7   adj_close                941 non-null    float64
 8   volume                   941 non-null    int64
 9   type                     941 non-null    object
 10  ema_adj_close_200p       742 non-null    float32
 11  ema_adj_close_200p_diff  742 non-null    float32
 12  ema_close_200p           742 non-null    float32
 13  ema_close_200p_diff      742 non-null    float32
 14  rsi                      927 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.7+ KB
Ticker: LREN3.SA - Shape (6006, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6006 entries, 0 to 6005
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6006 non-null   object
 1   open_time                6006 non-null   int64
 2   ticker                   6006 non-null   object
 3   open                     6006 non-null   float64
 4   high                     6006 non-null   float64
 5   low                      6006 non-null   float64
 6   close                    6006 non-null   float64
 7   adj_close                6006 non-null   float64
 8   volume                   6006 non-null   int64
 9   type                     6006 non-null   object
 10  ema_adj_close_200p       5807 non-null   float32
 11  ema_adj_close_200p_diff  5807 non-null   float32
 12  ema_close_200p           5807 non-null   float32
 13  ema_close_200p_diff      5807 non-null   float32
 14  rsi                      5984 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.1+ KB
Ticker: VIFI11.SA - Shape (865, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 865 entries, 0 to 864
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              865 non-null    object
 1   open_time                865 non-null    int64
 2   ticker                   865 non-null    object
 3   open                     865 non-null    float64
 4   high                     865 non-null    float64
 5   low                      865 non-null    float64
 6   close                    865 non-null    float64
 7   adj_close                865 non-null    float64
 8   volume                   865 non-null    int64
 9   type                     865 non-null    object
 10  ema_adj_close_200p       666 non-null    float32
 11  ema_adj_close_200p_diff  666 non-null    float32
 12  ema_close_200p           666 non-null    float32
 13  ema_close_200p_diff      666 non-null    float32
 14  rsi                      851 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 88.0+ KB
Ticker: BBSE3.SA - Shape (2634, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2634 entries, 0 to 2633
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2634 non-null   object
 1   open_time                2634 non-null   int64
 2   ticker                   2634 non-null   object
 3   open                     2634 non-null   float64
 4   high                     2634 non-null   float64
 5   low                      2634 non-null   float64
 6   close                    2634 non-null   float64
 7   adj_close                2634 non-null   float64
 8   volume                   2634 non-null   int64
 9   type                     2634 non-null   object
 10  ema_adj_close_200p       2435 non-null   float32
 11  ema_adj_close_200p_diff  2435 non-null   float32
 12  ema_close_200p           2435 non-null   float32
 13  ema_close_200p_diff      2435 non-null   float32
 14  rsi                      2620 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 267.6+ KB
Ticker: PRNR3.SA - Shape (942, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942 entries, 0 to 941
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              942 non-null    object
 1   open_time                942 non-null    int64
 2   ticker                   942 non-null    object
 3   open                     942 non-null    float64
 4   high                     942 non-null    float64
 5   low                      942 non-null    float64
 6   close                    942 non-null    float64
 7   adj_close                942 non-null    float64
 8   volume                   942 non-null    int64
 9   type                     942 non-null    object
 10  ema_adj_close_200p       743 non-null    float32
 11  ema_adj_close_200p_diff  743 non-null    float32
 12  ema_close_200p           743 non-null    float32
 13  ema_close_200p_diff      743 non-null    float32
 14  rsi                      928 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.8+ KB
Ticker: ANIM3.SA - Shape (2507, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2507 entries, 0 to 2506
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2507 non-null   object
 1   open_time                2507 non-null   int64
 2   ticker                   2507 non-null   object
 3   open                     2507 non-null   float64
 4   high                     2507 non-null   float64
 5   low                      2507 non-null   float64
 6   close                    2507 non-null   float64
 7   adj_close                2507 non-null   float64
 8   volume                   2507 non-null   int64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: CAML3.SA - Shape (1535, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1535 entries, 0 to 1534
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1535 non-null   object
 1   open_time                1535 non-null   int64
 2   ticker                   1535 non-null   object
 3   open                     1535 non-null   float64
 4   high                     1535 non-null   float64
 5   low                      1535 non-null   float64
 6   close                    1535 non-null   float64
 7   adj_close                1535 non-null   float64
 8   volume                   1535 non-null   int64
 9   type                     1535 non-null   object
 10  ema_adj_close_200p       1336 non-null   float32
 11  ema_adj_close_200p_diff  1336 non-null   float32
 12  ema_close_200p           1336 non-null   float32
 13  ema_close_200p_diff      1336 non-null   float32
 14  rsi                      1521 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 156.0+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
index 14 is out of bounds for axis 0 with size 1
Ticker: NCRA11.SA - Shape (1, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1 non-null      object
 1   open_time                1 non-null      int64
 2   ticker                   1 non-null      object
 3   open                     1 non-null      float64
 4   high                     1 non-null      float64
 5   low                      1 non-null      float64
 6   close                    1 non-null      float64
 7   adj_close                1 non-null      float64
 8   volume                   1 non-null      int64
 9   type                     1 non-null      object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
dtypes: float64(5), int64(2), object(7)
memory usage: 244.0+ bytes
Ticker: BTCI11.SA - Shape (1219, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1219 entries, 0 to 1218
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1219 non-null   object
 1   open_time                1219 non-null   int64
 2   ticker                   1219 non-null   object
 3   open                     1219 non-null   float64
 4   high                     1219 non-null   float64
 5   low                      1219 non-null   float64
 6   close                    1219 non-null   float64
 7   adj_close                1219 non-null   float64
 8   volume                   1219 non-null   int64
 9   type                     1219 non-null   object
 10  ema_adj_close_200p       1020 non-null   float32
 11  ema_adj_close_200p_diff  1020 non-null   float32
 12  ema_close_200p           1020 non-null   float32
 13  ema_close_200p_diff      1020 non-null   float32
 14  rsi                      1188 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 123.9+ KB
Ticker: SLED4.SA - Shape (5347, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5347 entries, 0 to 5346
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5347 non-null   object
 1   open_time                5347 non-null   int64
 2   ticker                   5347 non-null   object
 3   open                     5347 non-null   float64
 4   high                     5347 non-null   float64
 5   low                      5347 non-null   float64
 6   close                    5347 non-null   float64
 7   adj_close                5347 non-null   float64
 8   volume                   5347 non-null   int64
 9   type                     5347 non-null   object
 10  ema_adj_close_200p       5148 non-null   float32
 11  ema_adj_close_200p_diff  5148 non-null   float32
 12  ema_close_200p           5148 non-null   float32
 13  ema_close_200p_diff      5148 non-null   float32
 14  rsi                      5333 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 543.2+ KB
Ticker: BALM3.SA - Shape (5615, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5615 entries, 0 to 5614
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5615 non-null   object
 1   open_time                5615 non-null   int64
 2   ticker                   5615 non-null   object
 3   open                     5615 non-null   float64
 4   high                     5615 non-null   float64
 5   low                      5615 non-null   float64
 6   close                    5615 non-null   float64
 7   adj_close                5615 non-null   float64
 8   volume                   5615 non-null   int64
 9   type                     5615 non-null   object
 10  ema_adj_close_200p       5416 non-null   float32
 11  ema_adj_close_200p_diff  5416 non-null   float32
 12  ema_close_200p           5416 non-null   float32
 13  ema_close_200p_diff      5416 non-null   float32
 14  rsi                      5601 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 570.4+ KB
Ticker: CEGR3.SA - Shape (5773, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5773 entries, 0 to 5772
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5773 non-null   object
 1   open_time                5773 non-null   int64
 2   ticker                   5773 non-null   object
 3   open                     5773 non-null   float64
 4   high                     5773 non-null   float64
 5   low                      5773 non-null   float64
 6   close                    5773 non-null   float64
 7   adj_close                5773 non-null   float64
 8   volume                   5773 non-null   int64
 9   type                     5773 non-null   object
 10  ema_adj_close_200p       5574 non-null   float32
 11  ema_adj_close_200p_diff  5574 non-null   float32
 12  ema_close_200p           5574 non-null   float32
 13  ema_close_200p_diff      5574 non-null   float32
 14  rsi                      5725 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 586.4+ KB
Ticker: BRGE7.SA - Shape (4119, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4119 non-null   object
 1   open_time                4119 non-null   int64
 2   ticker                   4119 non-null   object
 3   open                     4119 non-null   float64
 4   high                     4119 non-null   float64
 5   low                      4119 non-null   float64
 6   close                    4119 non-null   float64
 7   adj_close                4119 non-null   float64
 8   volume                   4119 non-null   int64
 9   type                     4119 non-null   object
 10  ema_adj_close_200p       3920 non-null   float32
 11  ema_adj_close_200p_diff  3920 non-null   float32
 12  ema_close_200p           3920 non-null   float32
 13  ema_close_200p_diff      3920 non-null   float32
 14  rsi                      3937 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 418.5+ KB
Ticker: RSID3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: MANA11.SA - Shape (313, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 313 entries, 0 to 312
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              313 non-null    object
 1   open_time                313 non-null    int64
 2   ticker                   313 non-null    object
 3   open                     313 non-null    float64
 4   high                     313 non-null    float64
 5   low                      313 non-null    float64
 6   close                    313 non-null    float64
 7   adj_close                313 non-null    float64
 8   volume                   313 non-null    int64
 9   type                     313 non-null    object
 10  ema_adj_close_200p       114 non-null    float32
 11  ema_adj_close_200p_diff  114 non-null    float32
 12  ema_close_200p           114 non-null    float32
 13  ema_close_200p_diff      114 non-null    float32
 14  rsi                      299 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 31.9+ KB
Ticker: BRIP11.SA - Shape (404, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              404 non-null    object
 1   open_time                404 non-null    int64
 2   ticker                   404 non-null    object
 3   open                     404 non-null    float64
 4   high                     404 non-null    float64
 5   low                      404 non-null    float64
 6   close                    404 non-null    float64
 7   adj_close                404 non-null    float64
 8   volume                   404 non-null    int64
 9   type                     404 non-null    object
 10  ema_adj_close_200p       205 non-null    float32
 11  ema_adj_close_200p_diff  205 non-null    float32
 12  ema_close_200p           205 non-null    float32
 13  ema_close_200p_diff      205 non-null    float32
 14  rsi                      390 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 41.2+ KB
Ticker: SBSP3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: CRPG6.SA - Shape (6005, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6005 entries, 0 to 6004
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6005 non-null   object
 1   open_time                6005 non-null   int64
 2   ticker                   6005 non-null   object
 3   open                     6005 non-null   float64
 4   high                     6005 non-null   float64
 5   low                      6005 non-null   float64
 6   close                    6005 non-null   float64
 7   adj_close                6005 non-null   float64
 8   volume                   6005 non-null   int64
 9   type                     6005 non-null   object
 10  ema_adj_close_200p       5806 non-null   float32
 11  ema_adj_close_200p_diff  5806 non-null   float32
 12  ema_close_200p           5806 non-null   float32
 13  ema_close_200p_diff      5806 non-null   float32
 14  rsi                      5965 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.0+ KB
Ticker: SEQR11.SA - Shape (690, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              690 non-null    object
 1   open_time                690 non-null    int64
 2   ticker                   690 non-null    object
 3   open                     690 non-null    float64
 4   high                     690 non-null    float64
 5   low                      690 non-null    float64
 6   close                    690 non-null    float64
 7   adj_close                690 non-null    float64
 8   volume                   690 non-null    int64
 9   type                     690 non-null    object
 10  ema_adj_close_200p       491 non-null    float32
 11  ema_adj_close_200p_diff  491 non-null    float32
 12  ema_close_200p           491 non-null    float32
 13  ema_close_200p_diff      491 non-null    float32
 14  rsi                      676 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 70.2+ KB
Ticker: SUZB3.SA - Shape (4716, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4716 entries, 0 to 4715
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4716 non-null   object
 1   open_time                4716 non-null   int64
 2   ticker                   4716 non-null   object
 3   open                     4716 non-null   float64
 4   high                     4716 non-null   float64
 5   low                      4716 non-null   float64
 6   close                    4716 non-null   float64
 7   adj_close                4716 non-null   float64
 8   volume                   4716 non-null   int64
 9   type                     4716 non-null   object
 10  ema_adj_close_200p       4517 non-null   float32
 11  ema_adj_close_200p_diff  4517 non-null   float32
 12  ema_close_200p           4517 non-null   float32
 13  ema_close_200p_diff      4517 non-null   float32
 14  rsi                      4702 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 479.1+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: TSER11.SA - Shape (135, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              135 non-null    object
 1   open_time                135 non-null    int64
 2   ticker                   135 non-null    object
 3   open                     135 non-null    float64
 4   high                     135 non-null    float64
 5   low                      135 non-null    float64
 6   close                    135 non-null    float64
 7   adj_close                135 non-null    float64
 8   volume                   135 non-null    int64
 9   type                     135 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      121 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 15.9+ KB
Ticker: ITIT11.SA - Shape (426, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              426 non-null    object
 1   open_time                426 non-null    int64
 2   ticker                   426 non-null    object
 3   open                     426 non-null    float64
 4   high                     426 non-null    float64
 5   low                      426 non-null    float64
 6   close                    426 non-null    float64
 7   adj_close                426 non-null    float64
 8   volume                   426 non-null    int64
 9   type                     426 non-null    object
 10  ema_adj_close_200p       227 non-null    float32
 11  ema_adj_close_200p_diff  227 non-null    float32
 12  ema_close_200p           227 non-null    float32
 13  ema_close_200p_diff      227 non-null    float32
 14  rsi                      412 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 43.4+ KB
Ticker: KNRE11.SA - Shape (1528, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1528 entries, 0 to 1527
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1528 non-null   object
 1   open_time                1528 non-null   int64
 2   ticker                   1528 non-null   object
 3   open                     1528 non-null   float64
 4   high                     1528 non-null   float64
 5   low                      1528 non-null   float64
 6   close                    1528 non-null   float64
 7   adj_close                1528 non-null   float64
 8   volume                   1528 non-null   int64
 9   type                     1528 non-null   object
 10  ema_adj_close_200p       1329 non-null   float32
 11  ema_adj_close_200p_diff  1329 non-null   float32
 12  ema_close_200p           1329 non-null   float32
 13  ema_close_200p_diff      1329 non-null   float32
 14  rsi                      1514 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 155.3+ KB
Ticker: FIIB11.SA - Shape (2318, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2318 non-null   object
 1   open_time                2318 non-null   int64
 2   ticker                   2318 non-null   object
 3   open                     2318 non-null   float64
 4   high                     2318 non-null   float64
 5   low                      2318 non-null   float64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: RCSL4.SA - Shape (6003, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6003 entries, 0 to 6002
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6003 non-null   object
 1   open_time                6003 non-null   int64
 2   ticker                   6003 non-null   object
 3   open                     6003 non-null   float64
 4   high                     6003 non-null   float64
 5   low                      6003 non-null   float64
 6   close                    6003 non-null   float64
 7   adj_close                6003 non-null   float64
 8   volume                   6003 non-null   int64
 9   type                     6003 non-null   object
 10  ema_adj_close_200p       5804 non-null   float32
 11  ema_adj_close_200p_diff  5804 non-null   float32
 12  ema_close_200p           5804 non-null   float32
 13  ema_close_200p_diff      5804 non-null   float32
 14  rsi                      5989 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.8+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: BROF11.SA - Shape (164, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              164 non-null    object
 1   open_time                164 non-null    int64
 2   ticker                   164 non-null    object
 3   open                     164 non-null    float64
 4   high                     164 non-null    float64
 5   low                      164 non-null    float64
 6   close                    164 non-null    float64
 7   adj_close                164 non-null    float64
 8   volume                   164 non-null    int64
 9   type                     164 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      150 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 19.3+ KB
Ticker: AHEB6.SA - Shape (4093, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4093 entries, 0 to 4092
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4093 non-null   object
 1   open_time                4093 non-null   int64
 2   ticker                   4093 non-null   object
 3   open                     4093 non-null   float64
 4   high                     4093 non-null   float64
 5   low                      4093 non-null   float64
 6   close                    4093 non-null   float64
 7   adj_close                4093 non-null   float64
 8   volume                   4093 non-null   int64
 9   type                     4093 non-null   object
 10  ema_adj_close_200p       3894 non-null   float32
 11  ema_adj_close_200p_diff  3894 non-null   float32
 12  ema_close_200p           3894 non-null   float32
 13  ema_close_200p_diff      3894 non-null   float32
 14  rsi                      3410 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 415.8+ KB
Ticker: LVBI11.SA - Shape (918, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              918 non-null    object
 1   open_time                918 non-null    int64
 2   ticker                   918 non-null    object
 3   open                     918 non-null    float64
 4   high                     918 non-null    float64
 5   low                      918 non-null    float64
 6   close                    918 non-null    float64
 7   adj_close                918 non-null    float64
 8   volume                   918 non-null    int64
 9   type                     918 non-null    object
 10  ema_adj_close_200p       719 non-null    float32
 11  ema_adj_close_200p_diff  719 non-null    float32
 12  ema_close_200p           719 non-null    float32
 13  ema_close_200p_diff      719 non-null    float32
 14  rsi                      904 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 93.4+ KB
Ticker: KNOX11.SA - Shape (629, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 629 entries, 0 to 628
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              629 non-null    object
 1   open_time                629 non-null    int64
 2   ticker                   629 non-null    object
 3   open                     629 non-null    float64
 4   high                     629 non-null    float64
 5   low                      629 non-null    float64
 6   close                    629 non-null    float64
 7   adj_close                629 non-null    float64
 8   volume                   629 non-null    int64
 9   type                     629 non-null    object
 10  ema_adj_close_200p       430 non-null    float32
 11  ema_adj_close_200p_diff  430 non-null    float32
 12  ema_close_200p           430 non-null    float32
 13  ema_close_200p_diff      430 non-null    float32
 14  rsi                      615 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 64.0+ KB
Ticker: ONEF11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
index 14 is out of bounds for axis 0 with size 1
Ticker: KDIF11.SA - Shape (1, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1 non-null      object
 1   open_time                1 non-null      int64
 2   ticker                   1 non-null      object
 3   open                     1 non-null      float64
 4   high                     1 non-null      float64
 5   low                      1 non-null      float64
 6   close                    1 non-null      float64
 7   adj_close                1 non-null      float64
 8   volume                   1 non-null      int64
 9   type                     1 non-null      object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
dtypes: float64(5), int64(2), object(7)
memory usage: 244.0+ bytes
Ticker: CASN4.SA - Shape (3979, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3979 entries, 0 to 3978
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3979 non-null   object
 1   open_time                3979 non-null   int64
 2   ticker                   3979 non-null   object
 3   open                     3979 non-null   float64
 4   high                     3979 non-null   float64
 5   low                      3979 non-null   float64
 6   close                    3979 non-null   float64
 7   adj_close                3979 non-null   float64
 8   volume                   3979 non-null   int64
 9   type                     3979 non-null   object
 10  ema_adj_close_200p       3780 non-null   float32
 11  ema_adj_close_200p_diff  3780 non-null   float32
 12  ema_close_200p           3780 non-null   float32
 13  ema_close_200p_diff      3780 non-null   float32
 14  rsi                      3869 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 404.2+ KB
Ticker: CXTL11.SA - Shape (2317, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2317 entries, 0 to 2316
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2317 non-null   object
 1   open_time                2317 non-null   int64
 2   ticker                   2317 non-null   object
 3   open                     2317 non-null   float64
 4   high                     2317 non-null   float64
 5   low                      2317 non-null   float64
 6   close                    2317 non-null   float64
 7   adj_close                2317 non-null   float64
 8   volume                   2317 non-null   int64
 9   type                     2317 non-null   object
 10  ema_adj_close_200p       2118 non-null   float32
 11  ema_adj_close_200p_diff  2118 non-null   float32
 12  ema_close_200p           2118 non-null   float32
 13  ema_close_200p_diff      2118 non-null   float32
 14  rsi                      2303 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.4+ KB
Ticker: BREV11.SA - Shape (903, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903 entries, 0 to 902
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              903 non-null    object
 1   open_time                903 non-null    int64
 2   ticker                   903 non-null    object
 3   open                     903 non-null    float64
 4   high                     903 non-null    float64
 5   low                      903 non-null    float64
 6   close                    903 non-null    float64
 7   adj_close                903 non-null    float64
 8   volume                   903 non-null    int64
 9   type                     903 non-null    object
 10  ema_adj_close_200p       704 non-null    float32
 11  ema_adj_close_200p_diff  704 non-null    float32
 12  ema_close_200p           704 non-null    float32
 13  ema_close_200p_diff      704 non-null    float32
 14  rsi                      792 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 91.8+ KB
Ticker: VCJR11.SA - Shape (941, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              941 non-null    object
 1   open_time                941 non-null    int64
 2   ticker                   941 non-null    object
 3   open                     941 non-null    float64
 4   high                     941 non-null    float64
 5   low                      941 non-null    float64
 6   close                    941 non-null    float64
 7   adj_close                941 non-null    float64
 8   volume                   941 non-null    int64
 9   type                     941 non-null    object
 10  ema_adj_close_200p       742 non-null    float32
 11  ema_adj_close_200p_diff  742 non-null    float32
 12  ema_close_200p           742 non-null    float32
 13  ema_close_200p_diff      742 non-null    float32
 14  rsi                      927 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.7+ KB
Ticker: CXCE11B.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: MFII11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: GGBR3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: TAEE3.SA - Shape (4078, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4078 entries, 0 to 4077
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4078 non-null   object
 1   open_time                4078 non-null   int64
 2   ticker                   4078 non-null   object
 3   open                     4078 non-null   float64
 4   high                     4078 non-null   float64
 5   low                      4078 non-null   float64
 6   close                    4078 non-null   float64
 7   adj_close                4078 non-null   float64
 8   volume                   4078 non-null   int64
 9   type                     4078 non-null   object
 10  ema_adj_close_200p       3879 non-null   float32
 11  ema_adj_close_200p_diff  3879 non-null   float32
 12  ema_close_200p           3879 non-null   float32
 13  ema_close_200p_diff      3879 non-null   float32
 14  rsi                      3504 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 414.3+ KB

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: AALR3.SA - Shape (1765, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1765 entries, 0 to 1764
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1765 non-null   object
 1   open_time                1765 non-null   int64
 2   ticker                   1765 non-null   object
 3   open                     1765 non-null   float64
 4   high                     1765 non-null   float64
 5   low                      1765 non-null   float64
 6   close                    1765 non-null   float64
 7   adj_close                1765 non-null   float64
 8   volume                   1765 non-null   int64
 9   type                     1765 non-null   object
 10  ema_adj_close_200p       1566 non-null   float32
 11  ema_adj_close_200p_diff  1566 non-null   float32
 12  ema_close_200p           1566 non-null   float32
 13  ema_close_200p_diff      1566 non-null   float32
 14  rsi                      1751 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 179.4+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: BRLA11.SA - Shape (124, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              124 non-null    object
 1   open_time                124 non-null    int64
 2   ticker                   124 non-null    object
 3   open                     124 non-null    float64
 4   high                     124 non-null    float64
 5   low                      124 non-null    float64
 6   close                    124 non-null    float64
 7   adj_close                124 non-null    float64
 8   volume                   124 non-null    int64
 9   type                     124 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      110 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 14.7+ KB
Ticker: OIBR4.SA - Shape (5374, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5374 entries, 0 to 5373
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5374 non-null   object
 1   open_time                5374 non-null   int64
 2   ticker                   5374 non-null   object
 3   open                     5374 non-null   float64
 4   high                     5374 non-null   float64
 5   low                      5374 non-null   float64
 6   close                    5374 non-null   float64
 7   adj_close                5374 non-null   float64
 8   volume                   5374 non-null   int64
 9   type                     5374 non-null   object
 10  ema_adj_close_200p       5175 non-null   float32
 11  ema_adj_close_200p_diff  5175 non-null   float32
 12  ema_close_200p           5175 non-null   float32
 13  ema_close_200p_diff      5175 non-null   float32
 14  rsi                      5360 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 545.9+ KB
Ticker: XPCI11.SA - Shape (941, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              941 non-null    object
 1   open_time                941 non-null    int64
 2   ticker                   941 non-null    object
 3   open                     941 non-null    float64
 4   high                     941 non-null    float64
 5   low                      941 non-null    float64
 6   close                    941 non-null    float64
 7   adj_close                941 non-null    float64
 8   volume                   941 non-null    int64
 9   type                     941 non-null    object
 10  ema_adj_close_200p       742 non-null    float32
 11  ema_adj_close_200p_diff  742 non-null    float32
 12  ema_close_200p           742 non-null    float32
 13  ema_close_200p_diff      742 non-null    float32
 14  rsi                      927 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.7+ KB
Ticker: MBLY3.SA - Shape (701, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              701 non-null    object
 1   open_time                701 non-null    int64
 2   ticker                   701 non-null    object
 3   open                     701 non-null    float64
 4   high                     701 non-null    float64
 5   low                      701 non-null    float64
 6   close                    701 non-null    float64
 7   adj_close                701 non-null    float64
 8   volume                   701 non-null    int64
 9   type                     701 non-null    object
 10  ema_adj_close_200p       502 non-null    float32
 11  ema_adj_close_200p_diff  502 non-null    float32
 12  ema_close_200p           502 non-null    float32
 13  ema_close_200p_diff      502 non-null    float32
 14  rsi                      687 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 71.3+ KB
Ticker: CEDO3.SA - Shape (5972, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5972 entries, 0 to 5971
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5972 non-null   object
 1   open_time                5972 non-null   int64
 2   ticker                   5972 non-null   object
 3   open                     5972 non-null   float64
 4   high                     5972 non-null   float64
 5   low                      5972 non-null   float64
 6   close                    5972 non-null   float64
 7   adj_close                5972 non-null   float64
 8   volume                   5972 non-null   int64
 9   type                     5972 non-null   object
 10  ema_adj_close_200p       5773 non-null   float32
 11  ema_adj_close_200p_diff  5773 non-null   float32
 12  ema_close_200p           5773 non-null   float32
 13  ema_close_200p_diff      5773 non-null   float32
 14  rsi                      5913 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 606.7+ KB
Ticker: EMBR3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: HTMX11.SA - Shape (783, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783 entries, 0 to 782
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              783 non-null    object
 1   open_time                783 non-null    int64
 2   ticker                   783 non-null    object
 3   open                     783 non-null    float64
 4   high                     783 non-null    float64
 5   low                      783 non-null    float64
 6   close                    783 non-null    float64
 7   adj_close                783 non-null    float64
 8   volume                   783 non-null    int64
 9   type                     783 non-null    object
 10  ema_adj_close_200p       584 non-null    float32
 11  ema_adj_close_200p_diff  584 non-null    float32
 12  ema_close_200p           584 non-null    float32
 13  ema_close_200p_diff      584 non-null    float32
 14  rsi                      769 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 79.7+ KB
Ticker: ECOR3.SA - Shape (3394, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3394 entries, 0 to 3393
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3394 non-null   object
 1   open_time                3394 non-null   int64
 2   ticker                   3394 non-null   object
 3   open                     3394 non-null   float64
 4   high                     3394 non-null   float64
 5   low                      3394 non-null   float64
 6   close                    3394 non-null   float64
 7   adj_close                3394 non-null   float64
 8   volume                   3394 non-null   int64
 9   type                     3394 non-null   object
 10  ema_adj_close_200p       3195 non-null   float32
 11  ema_adj_close_200p_diff  3195 non-null   float32
 12  ema_close_200p           3195 non-null   float32
 13  ema_close_200p_diff      3195 non-null   float32
 14  rsi                      3380 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 344.8+ KB
Ticker: FIQE3.SA - Shape (585, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 585 entries, 0 to 584
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              585 non-null    object
 1   open_time                585 non-null    int64
 2   ticker                   585 non-null    object
 3   open                     585 non-null    float64
 4   high                     585 non-null    float64
 5   low                      585 non-null    float64
 6   close                    585 non-null    float64
 7   adj_close                585 non-null    float64
 8   volume                   585 non-null    int64
 9   type                     585 non-null    object
 10  ema_adj_close_200p       386 non-null    float32
 11  ema_adj_close_200p_diff  386 non-null    float32
 12  ema_close_200p           386 non-null    float32
 13  ema_close_200p_diff      386 non-null    float32
 14  rsi                      571 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 59.5+ KB
Ticker: URPR11.SA - Shape (810, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 810 entries, 0 to 809
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              810 non-null    object
 1   open_time                810 non-null    int64
 2   ticker                   810 non-null    object
 3   open                     810 non-null    float64
 4   high                     810 non-null    float64
 5   low                      810 non-null    float64
 6   close                    810 non-null    float64
 7   adj_close                810 non-null    float64
 8   volume                   810 non-null    int64
 9   type                     810 non-null    object
 10  ema_adj_close_200p       611 non-null    float32
 11  ema_adj_close_200p_diff  611 non-null    float32
 12  ema_close_200p           611 non-null    float32
 13  ema_close_200p_diff      611 non-null    float32
 14  rsi                      796 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 82.4+ KB
Ticker: CLSA3.SA - Shape (583, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              583 non-null    object
 1   open_time                583 non-null    int64
 2   ticker                   583 non-null    object
 3   open                     583 non-null    float64
 4   high                     583 non-null    float64
 5   low                      583 non-null    float64
 6   close                    583 non-null    float64
 7   adj_close                583 non-null    float64
 8   volume                   583 non-null    int64
 9   type                     583 non-null    object
 10  ema_adj_close_200p       384 non-null    float32
 11  ema_adj_close_200p_diff  384 non-null    float32
 12  ema_close_200p           384 non-null    float32
 13  ema_close_200p_diff      384 non-null    float32
 14  rsi                      569 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 59.3+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: ASRF11.SA - Shape (74, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              74 non-null     object
 1   open_time                74 non-null     int64
 2   ticker                   74 non-null     object
 3   open                     74 non-null     float64
 4   high                     74 non-null     float64
 5   low                      74 non-null     float64
 6   close                    74 non-null     float64
 7   adj_close                74 non-null     float64
 8   volume                   74 non-null     int64
 9   type                     74 non-null     object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      0 non-null      float64
dtypes: float64(6), int64(2), object(7)
memory usage: 8.8+ KB
Ticker: BDIF11.SA - Shape (652, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              652 non-null    object
 1   open_time                652 non-null    int64
 2   ticker                   652 non-null    object
 3   open                     652 non-null    float64
 4   high                     652 non-null    float64
 5   low                      652 non-null    float64
 6   close                    652 non-null    float64
 7   adj_close                652 non-null    float64
 8   volume                   652 non-null    int64
 9   type                     652 non-null    object
 10  ema_adj_close_200p       453 non-null    float32
 11  ema_adj_close_200p_diff  453 non-null    float32
 12  ema_close_200p           453 non-null    float32
 13  ema_close_200p_diff      453 non-null    float32
 14  rsi                      638 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 66.3+ KB
Ticker: MAPT4.SA - Shape (5987, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5987 entries, 0 to 5986
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5987 non-null   object
 1   open_time                5987 non-null   int64
 2   ticker                   5987 non-null   object
 3   open                     5987 non-null   float64
 4   high                     5987 non-null   float64
 5   low                      5987 non-null   float64
 6   close                    5987 non-null   float64
 7   adj_close                5987 non-null   float64
 8   volume                   5987 non-null   int64
 9   type                     5987 non-null   object
 10  ema_adj_close_200p       5788 non-null   float32
 11  ema_adj_close_200p_diff  5788 non-null   float32
 12  ema_close_200p           5788 non-null   float32
 13  ema_close_200p_diff      5788 non-null   float32
 14  rsi                      5973 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 608.2+ KB
Ticker: BEES3.SA - Shape (6004, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6004 entries, 0 to 6003
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6004 non-null   object
 1   open_time                6004 non-null   int64
 2   ticker                   6004 non-null   object
 3   open                     6004 non-null   float64
 4   high                     6004 non-null   float64
 5   low                      6004 non-null   float64
 6   close                    6004 non-null   float64
 7   adj_close                6004 non-null   float64
 8   volume                   6004 non-null   int64
 9   type                     6004 non-null   object
 10  ema_adj_close_200p       5805 non-null   float32
 11  ema_adj_close_200p_diff  5805 non-null   float32
 12  ema_close_200p           5805 non-null   float32
 13  ema_close_200p_diff      5805 non-null   float32
 14  rsi                      5990 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.9+ KB
Ticker: FRIO3.SA - Shape (4126, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4126 entries, 0 to 4125
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4126 non-null   object
 1   open_time                4126 non-null   int64
 2   ticker                   4126 non-null   object
 3   open                     4126 non-null   float64
 4   high                     4126 non-null   float64
 5   low                      4126 non-null   float64
 6   close                    4126 non-null   float64
 7   adj_close                4126 non-null   float64
 8   volume                   4126 non-null   int64
 9   type                     4126 non-null   object
 10  ema_adj_close_200p       3927 non-null   float32
 11  ema_adj_close_200p_diff  3927 non-null   float32
 12  ema_close_200p           3927 non-null   float32
 13  ema_close_200p_diff      3927 non-null   float32
 14  rsi                      4112 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 419.2+ KB
Ticker: TEKA4.SA - Shape (5178, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5178 entries, 0 to 5177
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5178 non-null   object
 1   open_time                5178 non-null   int64
 2   ticker                   5178 non-null   object
 3   open                     5178 non-null   float64
 4   high                     5178 non-null   float64
 5   low                      5178 non-null   float64
 6   close                    5178 non-null   float64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: CMIG3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: RPAD6.SA - Shape (6004, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6004 entries, 0 to 6003
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6004 non-null   object
 1   open_time                6004 non-null   int64
 2   ticker                   6004 non-null   object
 3   open                     6004 non-null   float64
 4   high                     6004 non-null   float64
 5   low                      6004 non-null   float64
 6   close                    6004 non-null   float64
 7   adj_close                6004 non-null   float64
 8   volume                   6004 non-null   int64
 9   type                     6004 non-null   object
 10  ema_adj_close_200p       5805 non-null   float32
 11  ema_adj_close_200p_diff  5805 non-null   float32
 12  ema_close_200p           5805 non-null   float32
 13  ema_close_200p_diff      5805 non-null   float32
 14  rsi                      5990 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.9+ KB
Ticker: MGFF11.SA - Shape (1405, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1405 entries, 0 to 1404
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1405 non-null   object
 1   open_time                1405 non-null   int64
 2   ticker                   1405 non-null   object
 3   open                     1405 non-null   float64
 4   high                     1405 non-null   float64
 5   low                      1405 non-null   float64
 6   close                    1405 non-null   float64
 7   adj_close                1405 non-null   float64
 8   volume                   1405 non-null   int64
 9   type                     1405 non-null   object
 10  ema_adj_close_200p       1206 non-null   float32
 11  ema_adj_close_200p_diff  1206 non-null   float32
 12  ema_close_200p           1206 non-null   float32
 13  ema_close_200p_diff      1206 non-null   float32
 14  rsi                      1391 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 142.8+ KB
Ticker: BLMG11.SA - Shape (697, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 697 entries, 0 to 696
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              697 non-null    object
 1   open_time                697 non-null    int64
 2   ticker                   697 non-null    object
 3   open                     697 non-null    float64
 4   high                     697 non-null    float64
 5   low                      697 non-null    float64
 6   close                    697 non-null    float64
 7   adj_close                697 non-null    float64
 8   volume                   697 non-null    int64
 9   type                     697 non-null    object
 10  ema_adj_close_200p       498 non-null    float32
 11  ema_adj_close_200p_diff  498 non-null    float32
 12  ema_close_200p           498 non-null    float32
 13  ema_close_200p_diff      498 non-null    float32
 14  rsi                      683 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 70.9+ KB
Ticker: STBP3.SA - Shape (3657, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3657 entries, 0 to 3656
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3657 non-null   object
 1   open_time                3657 non-null   int64
 2   ticker                   3657 non-null   object
 3   open                     3657 non-null   float64
 4   high                     3657 non-null   float64
 5   low                      3657 non-null   float64
 6   close                    3657 non-null   float64
 7   adj_close                3657 non-null   float64
 8   volume                   3657 non-null   int64
 9   type                     3657 non-null   object
 10  ema_adj_close_200p       3458 non-null   float32
 11  ema_adj_close_200p_diff  3458 non-null   float32
 12  ema_close_200p           3458 non-null   float32
 13  ema_close_200p_diff      3458 non-null   float32
 14  rsi                      3397 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 371.5+ KB
Ticker: OUFF11.SA - Shape (1090, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1090 entries, 0 to 1089
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1090 non-null   object
 1   open_time                1090 non-null   int64
 2   ticker                   1090 non-null   object
 3   open                     1090 non-null   float64
 4   high                     1090 non-null   float64
 5   low                      1090 non-null   float64
 6   close                    1090 non-null   float64
 7   adj_close                1090 non-null   float64
 8   volume                   1090 non-null   int64
 9   type                     1090 non-null   object
 10  ema_adj_close_200p       891 non-null    float32
 11  ema_adj_close_200p_diff  891 non-null    float32
 12  ema_close_200p           891 non-null    float32
 13  ema_close_200p_diff      891 non-null    float32
 14  rsi                      1076 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 110.8+ KB
Ticker: AFHI11.SA - Shape (665, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 665 entries, 0 to 664
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              665 non-null    object
 1   open_time                665 non-null    int64
 2   ticker                   665 non-null    object
 3   open                     665 non-null    float64
 4   high                     665 non-null    float64
 5   low                      665 non-null    float64
 6   close                    665 non-null    float64
 7   adj_close                665 non-null    float64
 8   volume                   665 non-null    int64
 9   type                     665 non-null    object
 10  ema_adj_close_200p       466 non-null    float32
 11  ema_adj_close_200p_diff  466 non-null    float32
 12  ema_close_200p           466 non-null    float32
 13  ema_close_200p_diff      466 non-null    float32
 14  rsi                      651 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 67.7+ KB
Ticker: CEED4.SA - Shape (3196, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3196 entries, 0 to 3195
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3196 non-null   object
 1   open_time                3196 non-null   int64
 2   ticker                   3196 non-null   object
 3   open                     3196 non-null   float64
 4   high                     3196 non-null   float64
 5   low                      3196 non-null   float64
 6   close                    3196 non-null   float64
 7   adj_close                3196 non-null   float64
 8   volume                   3196 non-null   int64
 9   type                     3196 non-null   object
 10  ema_adj_close_200p       2997 non-null   float32
 11  ema_adj_close_200p_diff  2997 non-null   float32
 12  ema_close_200p           2997 non-null   float32
 13  ema_close_200p_diff      2997 non-null   float32
 14  rsi                      3182 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 324.7+ KB
Ticker: FHER3.SA - Shape (4128, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4128 entries, 0 to 4127
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4128 non-null   object
 1   open_time                4128 non-null   int64
 2   ticker                   4128 non-null   object
 3   open                     4128 non-null   float64
 4   high                     4128 non-null   float64
 5   low                      4128 non-null   float64
 6   close                    4128 non-null   float64
 7   adj_close                4128 non-null   float64
 8   volume                   4128 non-null   int64
 9   type                     4128 non-null   object
 10  ema_adj_close_200p       3929 non-null   float32
 11  ema_adj_close_200p_diff  3929 non-null   float32
 12  ema_close_200p           3929 non-null   float32
 13  ema_close_200p_diff      3929 non-null   float32
 14  rsi                      4114 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 419.4+ KB
Ticker: RSPD11.SA - Shape (939, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              939 non-null    object
 1   open_time                939 non-null    int64
 2   ticker                   939 non-null    object
 3   open                     939 non-null    float64
 4   high                     939 non-null    float64
 5   low                      939 non-null    float64
 6   close                    939 non-null    float64
 7   adj_close                939 non-null    float64
 8   volume                   939 non-null    int64
 9   type                     939 non-null    object
 10  ema_adj_close_200p       740 non-null    float32
 11  ema_adj_close_200p_diff  740 non-null    float32
 12  ema_close_200p           740 non-null    float32
 13  ema_close_200p_diff      740 non-null    float32
 14  rsi                      704 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.5+ KB
Ticker: CEEB5.SA - Shape (3949, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3949 entries, 0 to 3948
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3949 non-null   object
 1   open_time                3949 non-null   int64
 2   ticker                   3949 non-null   object
 3   open                     3949 non-null   float64
 4   high                     3949 non-null   float64
 5   low                      3949 non-null   float64
 6   close                    3949 non-null   float64
 7   adj_close                3949 non-null   float64
 8   volume                   3949 non-null   int64
 9   type                     3949 non-null   object
 10  ema_adj_close_200p       3750 non-null   float32
 11  ema_adj_close_200p_diff  3750 non-null   float32
 12  ema_close_200p           3750 non-null   float32
 13  ema_close_200p_diff      3750 non-null   float32
 14  rsi                      3935 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.2+ KB
Ticker: BRGE3.SA - Shape (6004, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6004 entries, 0 to 6003
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6004 non-null   object
 1   open_time                6004 non-null   int64
 2   ticker                   6004 non-null   object
 3   open                     6004 non-null   float64
 4   high                     6004 non-null   float64
 5   low                      6004 non-null   float64
 6   close                    6004 non-null   float64
 7   adj_close                6004 non-null   float64
 8   volume                   6004 non-null   int64
 9   type                     6004 non-null   object
 10  ema_adj_close_200p       5805 non-null   float32
 11  ema_adj_close_200p_diff  5805 non-null   float32
 12  ema_close_200p           5805 non-null   float32
 13  ema_close_200p_diff      5805 non-null   float32
 14  rsi                      5990 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.9+ KB
Ticker: HGLG11.SA - Shape (3166, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3166 entries, 0 to 3165
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3166 non-null   object
 1   open_time                3166 non-null   int64
 2   ticker                   3166 non-null   object
 3   open                     3166 non-null   float64
 4   high                     3166 non-null   float64
 5   low                      3166 non-null   float64
 6   close                    3166 non-null   float64
 7   adj_close                3166 non-null   float64
 8   volume                   3166 non-null   int64
 9   type                     3166 non-null   object
 10  ema_adj_close_200p       2967 non-null   float32
 11  ema_adj_close_200p_diff  2967 non-null   float32
 12  ema_close_200p           2967 non-null   float32
 13  ema_close_200p_diff      2967 non-null   float32
 14  rsi                      3127 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 321.7+ KB
Ticker: FLRY3.SA - Shape (3463, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3463 entries, 0 to 3462
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3463 non-null   object
 1   open_time                3463 non-null   int64
 2   ticker                   3463 non-null   object
 3   open                     3463 non-null   float64
 4   high                     3463 non-null   float64
 5   low                      3463 non-null   float64
 6   close                    3463 non-null   float64
 7   adj_close                3463 non-null   float64
 8   volume                   3463 non-null   int64
 9   type                     3463 non-null   object
 10  ema_adj_close_200p       3264 non-null   float32
 11  ema_adj_close_200p_diff  3264 non-null   float32
 12  ema_close_200p           3264 non-null   float32
 13  ema_close_200p_diff      3264 non-null   float32
 14  rsi                      3449 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 351.8+ KB
Ticker: MGLU3.SA - Shape (3127, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3127 entries, 0 to 3126
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3127 non-null   object
 1   open_time                3127 non-null   int64
 2   ticker                   3127 non-null   object
 3   open                     3127 non-null   float64
 4   high                     3127 non-null   float64
 5   low                      3127 non-null   float64
 6   close                    3127 non-null   float64
 7   adj_close                3127 non-null   float64
 8   volume                   3127 non-null   int64
 9   type                     3127 non-null   object
 10  ema_adj_close_200p       2928 non-null   float32
 11  ema_adj_close_200p_diff  2928 non-null   float32
 12  ema_close_200p           2928 non-null   float32
 13  ema_close_200p_diff      2928 non-null   float32
 14  rsi                      3113 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 317.7+ KB
Ticker: SQIA3.SA - Shape (2650, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2650 entries, 0 to 2649
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2650 non-null   object
 1   open_time                2650 non-null   int64
 2   ticker                   2650 non-null   object
 3   open                     2650 non-null   float64
 4   high                     2650 non-null   float64
 5   low                      2650 non-null   float64
 6   close                    2650 non-null   float64
 7   adj_close                2650 non-null   float64
 8   volume                   2650 non-null   int64
 9   type                     2650 non-null   object
 10  ema_adj_close_200p       2451 non-null   float32
 11  ema_adj_close_200p_diff  2451 non-null   float32
 12  ema_close_200p           2451 non-null   float32
 13  ema_close_200p_diff      2451 non-null   float32
 14  rsi                      2636 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 269.3+ KB
Ticker: OUJP11.SA - Shape (1528, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1528 entries, 0 to 1527
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1528 non-null   object
 1   open_time                1528 non-null   int64
 2   ticker                   1528 non-null   object
 3   open                     1528 non-null   float64
 4   high                     1528 non-null   float64
 5   low                      1528 non-null   float64
 6   close                    1528 non-null   float64
 7   adj_close                1528 non-null   float64
 8   volume                   1528 non-null   int64
 9   type                     1528 non-null   object
 10  ema_adj_close_200p       1329 non-null   float32
 11  ema_adj_close_200p_diff  1329 non-null   float32
 12  ema_close_200p           1329 non-null   float32
 13  ema_close_200p_diff      1329 non-null   float32
 14  rsi                      1514 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 155.3+ KB
Ticker: HSLG11.SA - Shape (731, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              731 non-null    object
 1   open_time                731 non-null    int64
 2   ticker                   731 non-null    object
 3   open                     731 non-null    float64
 4   high                     731 non-null    float64
 5   low                      731 non-null    float64
 6   close                    731 non-null    float64
 7   adj_close                731 non-null    float64
 8   volume                   731 non-null    int64
 9   type                     731 non-null    object
 10  ema_adj_close_200p       532 non-null    float32

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: HETA3.SA - Shape (5711, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5711 entries, 0 to 5710
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5711 non-null   object
 1   open_time                5711 non-null   int64
 2   ticker                   5711 non-null   object
 3   open                     5711 non-null   float64
 4   high                     5711 non-null   float64
 5   low                      5711 non-null   float64
 6   close                    5711 non-null   float64
 7   adj_close                5711 non-null   float64
 8   volume                   5711 non-null   int64
 9   type                     5711 non-null   object
 10  ema_adj_close_200p       5512 non-null   float32
 11  ema_adj_close_200p_diff  5512 non-null   float32
 12  ema_close_200p           5512 non-null   float32
 13  ema_close_200p_diff      5512 non-null   float32
 14  rsi                      4104 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 580.2+ KB
Ticker: BLAU3.SA - Shape (655, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 655 entries, 0 to 654
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              655 non-null    object
 1   open_time                655 non-null    int64
 2   ticker                   655 non-null    object
 3   open                     655 non-null    float64
 4   high                     655 non-null    float64
 5   low                      655 non-null    float64
 6   close                    655 non-null    float64
 7   adj_close                655 non-null    float64
 8   volume                   655 non-null    int64
 9   type                     655 non-null    object
 10  ema_adj_close_200p       456 non-null    float32
 11  ema_adj_close_200p_diff  456 non-null    float32
 12  ema_close_200p           456 non-null    float32
 13  ema_close_200p_diff      456 non-null    float32
 14  rsi                      641 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 66.7+ KB
Ticker: CRIV3.SA - Shape (6005, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6005 entries, 0 to 6004
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6005 non-null   object
 1   open_time                6005 non-null   int64
 2   ticker                   6005 non-null   object
 3   open                     6005 non-null   float64
 4   high                     6005 non-null   float64
 5   low                      6005 non-null   float64
 6   close                    6005 non-null   float64
 7   adj_close                6005 non-null   float64
 8   volume                   6005 non-null   int64
 9   type                     6005 non-null   object
 10  ema_adj_close_200p       5806 non-null   float32
 11  ema_adj_close_200p_diff  5806 non-null   float32
 12  ema_close_200p           5806 non-null   float32
 13  ema_close_200p_diff      5806 non-null   float32
 14  rsi                      5991 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.0+ KB
Ticker: CORR4.SA - Shape (3893, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3893 entries, 0 to 3892
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3893 non-null   object
 1   open_time                3893 non-null   int64
 2   ticker                   3893 non-null   object
 3   open                     3893 non-null   float64
 4   high                     3893 non-null   float64
 5   low                      3893 non-null   float64
 6   close                    3893 non-null   float64
 7   adj_close                3893 non-null   float64
 8   volume                   3893 non-null   int64
 9   type                     3893 non-null   object
 10  ema_adj_close_200p       3694 non-null   float32
 11  ema_adj_close_200p_diff  3694 non-null   float32
 12  ema_close_200p           3694 non-null   float32
 13  ema_close_200p_diff      3694 non-null   float32
 14  rsi                      3412 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 395.5+ KB
Ticker: MNPR3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: REDE3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: CPLE6.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: VVPR11.SA - Shape (939, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              939 non-null    object
 1   open_time                939 non-null    int64
 2   ticker                   939 non-null    object
 3   open                     939 non-null    float64
 4   high                     939 non-null    float64
 5   low                      939 non-null    float64
 6   close                    939 non-null    float64
 7   adj_close                939 non-null    float64
 8   volume                   939 non-null    int64
 9   type                     939 non-null    object
 10  ema_adj_close_200p       740 non-null    float32
 11  ema_adj_close_200p_diff  740 non-null    float32
 12  ema_close_200p           740 non-null    float32
 13  ema_close_200p_diff      740 non-null    float32
 14  rsi                      925 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.5+ KB
Ticker: HGBS11.SA - Shape (2912, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2912 entries, 0 to 2911
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2912 non-null   object
 1   open_time                2912 non-null   int64
 2   ticker                   2912 non-null   object
 3   open                     2912 non-null   float64
 4   high                     2912 non-null   float64
 5   low                      2912 non-null   float64
 6   close                    2912 non-null   float64
 7   adj_close                2912 non-null   float64
 8   volume                   2912 non-null   int64
 9   type                     2912 non-null   object
 10  ema_adj_close_200p       2713 non-null   float32
 11  ema_adj_close_200p_diff  2713 non-null   float32
 12  ema_close_200p           2713 non-null   float32
 13  ema_close_200p_diff      2713 non-null   float32
 14  rsi                      2898 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 295.9+ KB
Ticker: NEXP3.SA - Shape (3991, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3991 entries, 0 to 3990
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3991 non-null   object
 1   open_time                3991 non-null   int64
 2   ticker                   3991 non-null   object
 3   open                     3991 non-null   float64
 4   high                     3991 non-null   float64
 5   low                      3991 non-null   float64
 6   close                    3991 non-null   float64
 7   adj_close                3991 non-null   float64
 8   volume                   3991 non-null   int64
 9   type                     3991 non-null   object
 10  ema_adj_close_200p       3792 non-null   float32
 11  ema_adj_close_200p_diff  3792 non-null   float32
 12  ema_close_200p           3792 non-null   float32
 13  ema_close_200p_diff      3792 non-null   float32
 14  rsi                      3977 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 405.5+ KB
Ticker: RBCO11.SA - Shape (852, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              852 non-null    object
 1   open_time                852 non-null    int64
 2   ticker                   852 non-null    object
 3   open                     852 non-null    float64
 4   high                     852 non-null    float64
 5   low                      852 non-null    float64
 6   close                    852 non-null    float64
 7   adj_close                852 non-null    float64
 8   volume                   852 non-null    int64
 9   type                     852 non-null    object
 10  ema_adj_close_200p       653 non-null    float32
 11  ema_adj_close_200p_diff  653 non-null    float32
 12  ema_close_200p           653 non-null    float32
 13  ema_close_200p_diff      653 non-null    float32
 14  rsi                      838 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 86.7+ KB
Ticker: HRDF11.SA - Shape (959, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 959 entries, 0 to 958
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              959 non-null    object
 1   open_time                959 non-null    int64
 2   ticker                   959 non-null    object
 3   open                     959 non-null    float64
 4   high                     959 non-null    float64
 5   low                      959 non-null    float64
 6   close                    959 non-null    float64
 7   adj_close                959 non-null    float64
 8   volume                   959 non-null    int64
 9   type                     959 non-null    object
 10  ema_adj_close_200p       760 non-null    float32
 11  ema_adj_close_200p_diff  760 non-null    float32
 12  ema_close_200p           760 non-null    float32
 13  ema_close_200p_diff      760 non-null    float32
 14  rsi                      945 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 97.5+ KB
Ticker: GFSA3.SA - Shape (5063, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5063 entries, 0 to 5062
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5063 non-null   object
 1   open_time                5063 non-null   int64
 2   ticker                   5063 non-null   object
 3   open                     5063 non-null   float64
 4   high                     5063 non-null   float64
 5   low                      5063 non-null   float64
 6   close                    5063 non-null   float64
 7   adj_close                5063 non-null   float64
 8   volume                   5063 non-null   int64
 9   type                     5063 non-null   object
 10  ema_adj_close_200p       4864 non-null   float32
 11  ema_adj_close_200p_diff  4864 non-null   float32
 12  ema_close_200p           4864 non-null   float32
 13  ema_close_200p_diff      4864 non-null   float32
 14  rsi                      4830 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 514.3+ KB
Ticker: SANB4.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: APXM11.SA - Shape (75, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              75 non-null     object
 1   open_time                75 non-null     int64
 2   ticker                   75 non-null     object
 3   open                     75 non-null     float64
 4   high                     75 non-null     float64
 5   low                      75 non-null     float64
 6   close                    75 non-null     float64
 7   adj_close                75 non-null     float64
 8   volume                   75 non-null     int64
 9   type                     75 non-null     object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      61 non-null     float64
dtypes: float64(6), int64(2), object(7)
memory usage: 8.9+ KB
Ticker: SAPR4.SA - Shape (3951, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3951 entries, 0 to 3950
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3951 non-null   object
 1   open_time                3951 non-null   int64
 2   ticker                   3951 non-null   object
 3   open                     3951 non-null   float64
 4   high                     3951 non-null   float64
 5   low                      3951 non-null   float64
 6   close                    3951 non-null   float64
 7   adj_close                3951 non-null   float64
 8   volume                   3951 non-null   int64
 9   type                     3951 non-null   object
 10  ema_adj_close_200p       3752 non-null   float32
 11  ema_adj_close_200p_diff  3752 non-null   float32
 12  ema_close_200p           3752 non-null   float32
 13  ema_close_200p_diff      3752 non-null   float32
 14  rsi                      3937 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.4+ KB
Ticker: SNSY6.SA - Shape (4163, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4163 entries, 0 to 4162
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4163 non-null   object
 1   open_time                4163 non-null   int64
 2   ticker                   4163 non-null   object
 3   open                     4163 non-null   float64
 4   high                     4163 non-null   float64
 5   low                      4163 non-null   float64
 6   close                    4163 non-null   float64
 7   adj_close                4163 non-null   float64
 8   volume                   4163 non-null   int64
 9   type                     4163 non-null   object
 10  ema_adj_close_200p       3964 non-null   float32
 11  ema_adj_close_200p_diff  3964 non-null   float32
 12  ema_close_200p           3964 non-null   float32
 13  ema_close_200p_diff      3964 non-null   float32
 14  rsi                      2938 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 422.9+ KB
Ticker: NEOE3.SA - Shape (1100, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1100 non-null   object
 1   open_time                1100 non-null   int64
 2   ticker                   1100 non-null   object
 3   open                     1100 non-null   float64
 4   high                     1100 non-null   float64
 5   low                      1100 non-null   float64
 6   close                    1100 non-null   float64
 7   adj_close                1100 non-null   float64
 8   volume                   1100 non-null   int64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: CEAB3.SA - Shape (1010, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1010 non-null   object
 1   open_time                1010 non-null   int64
 2   ticker                   1010 non-null   object
 3   open                     1010 non-null   float64
 4   high                     1010 non-null   float64
 5   low                      1010 non-null   float64
 6   close                    1010 non-null   float64
 7   adj_close                1010 non-null   float64
 8   volume                   1010 non-null   int64
 9   type                     1010 non-null   object
 10  ema_adj_close_200p       811 non-null    float32
 11  ema_adj_close_200p_diff  811 non-null    float32
 12  ema_close_200p           811 non-null    float32
 13  ema_close_200p_diff      811 non-null    float32
 14  rsi                      996 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 102.7+ KB
Ticker: CSRN3.SA - Shape (5951, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5951 entries, 0 to 5950
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5951 non-null   object
 1   open_time                5951 non-null   int64
 2   ticker                   5951 non-null   object
 3   open                     5951 non-null   float64
 4   high                     5951 non-null   float64
 5   low                      5951 non-null   float64
 6   close                    5951 non-null   float64
 7   adj_close                5951 non-null   float64
 8   volume                   5951 non-null   int64
 9   type                     5951 non-null   object
 10  ema_adj_close_200p       5752 non-null   float32
 11  ema_adj_close_200p_diff  5752 non-null   float32
 12  ema_close_200p           5752 non-null   float32
 13  ema_close_200p_diff      5752 non-null   float32
 14  rsi                      5920 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 604.5+ KB
Ticker: TRIS3.SA - Shape (4001, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4001 entries, 0 to 4000
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4001 non-null   object
 1   open_time                4001 non-null   int64
 2   ticker                   4001 non-null   object
 3   open                     4001 non-null   float64
 4   high                     4001 non-null   float64
 5   low                      4001 non-null   float64
 6   close                    4001 non-null   float64
 7   adj_close                4001 non-null   float64
 8   volume                   4001 non-null   int64
 9   type                     4001 non-null   object
 10  ema_adj_close_200p       3802 non-null   float32
 11  ema_adj_close_200p_diff  3802 non-null   float32
 12  ema_close_200p           3802 non-null   float32
 13  ema_close_200p_diff      3802 non-null   float32
 14  rsi                      3987 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 406.5+ KB
Ticker: CMIN3.SA - Shape (694, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              694 non-null    object
 1   open_time                694 non-null    int64
 2   ticker                   694 non-null    object
 3   open                     694 non-null    float64
 4   high                     694 non-null    float64
 5   low                      694 non-null    float64
 6   close                    694 non-null    float64
 7   adj_close                694 non-null    float64
 8   volume                   694 non-null    int64
 9   type                     694 non-null    object
 10  ema_adj_close_200p       495 non-null    float32
 11  ema_adj_close_200p_diff  495 non-null    float32
 12  ema_close_200p           495 non-null    float32
 13  ema_close_200p_diff      495 non-null    float32
 14  rsi                      680 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 70.6+ KB
Ticker: SOND3.SA - Shape (5513, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5513 entries, 0 to 5512
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5513 non-null   object
 1   open_time                5513 non-null   int64
 2   ticker                   5513 non-null   object
 3   open                     5513 non-null   float64
 4   high                     5513 non-null   float64
 5   low                      5513 non-null   float64
 6   close                    5513 non-null   float64
 7   adj_close                5513 non-null   float64
 8   volume                   5513 non-null   int64
 9   type                     5513 non-null   object
 10  ema_adj_close_200p       5314 non-null   float32
 11  ema_adj_close_200p_diff  5314 non-null   float32
 12  ema_close_200p           5314 non-null   float32
 13  ema_close_200p_diff      5314 non-null   float32
 14  rsi                      5476 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 560.0+ KB
Ticker: JGPX11.SA - Shape (502, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              502 non-null    object
 1   open_time                502 non-null    int64
 2   ticker                   502 non-null    object
 3   open                     502 non-null    float64
 4   high                     502 non-null    float64
 5   low                      502 non-null    float64
 6   close                    502 non-null    float64
 7   adj_close                502 non-null    float64
 8   volume                   502 non-null    int64
 9   type                     502 non-null    object
 10  ema_adj_close_200p       303 non-null    float32
 11  ema_adj_close_200p_diff  303 non-null    float32
 12  ema_close_200p           303 non-null    float32
 13  ema_close_200p_diff      303 non-null    float32
 14  rsi                      488 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 51.1+ KB
Ticker: MORE11.SA - Shape (430, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              430 non-null    object
 1   open_time                430 non-null    int64
 2   ticker                   430 non-null    object
 3   open                     430 non-null    float64
 4   high                     430 non-null    float64
 5   low                      430 non-null    float64
 6   close                    430 non-null    float64
 7   adj_close                430 non-null    float64
 8   volume                   430 non-null    int64
 9   type                     430 non-null    object
 10  ema_adj_close_200p       231 non-null    float32
 11  ema_adj_close_200p_diff  231 non-null    float32
 12  ema_close_200p           231 non-null    float32
 13  ema_close_200p_diff      231 non-null    float32
 14  rsi                      416 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 43.8+ KB
Ticker: TTEN3.SA - Shape (592, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              592 non-null    object
 1   open_time                592 non-null    int64
 2   ticker                   592 non-null    object
 3   open                     592 non-null    float64
 4   high                     592 non-null    float64
 5   low                      592 non-null    float64
 6   close                    592 non-null    float64
 7   adj_close                592 non-null    float64
 8   volume                   592 non-null    int64
 9   type                     592 non-null    object
 10  ema_adj_close_200p       393 non-null    float32
 11  ema_adj_close_200p_diff  393 non-null    float32
 12  ema_close_200p           393 non-null    float32
 13  ema_close_200p_diff      393 non-null    float32
 14  rsi                      578 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 60.3+ KB
Ticker: AHEB5.SA - Shape (4084, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4084 entries, 0 to 4083
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4084 non-null   object
 1   open_time                4084 non-null   int64
 2   ticker                   4084 non-null   object
 3   open                     4084 non-null   float64
 4   high                     4084 non-null   float64
 5   low                      4084 non-null   float64
 6   close                    4084 non-null   float64
 7   adj_close                4084 non-null   float64
 8   volume                   4084 non-null   int64
 9   type                     4084 non-null   object
 10  ema_adj_close_200p       3885 non-null   float32
 11  ema_adj_close_200p_diff  3885 non-null   float32
 12  ema_close_200p           3885 non-null   float32
 13  ema_close_200p_diff      3885 non-null   float32
 14  rsi                      3680 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 414.9+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: SPMO11.SA - Shape (54, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              54 non-null     object
 1   open_time                54 non-null     int64
 2   ticker                   54 non-null     object
 3   open                     54 non-null     float64
 4   high                     54 non-null     float64
 5   low                      54 non-null     float64
 6   close                    54 non-null     float64
 7   adj_close                54 non-null     float64
 8   volume                   54 non-null     int64
 9   type                     54 non-null     object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      18 non-null     float64
dtypes: float64(6), int64(2), object(7)
memory usage: 6.5+ KB
Ticker: RBRM11.SA - Shape (848, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848 entries, 0 to 847
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              848 non-null    object
 1   open_time                848 non-null    int64
 2   ticker                   848 non-null    object
 3   open                     848 non-null    float64
 4   high                     848 non-null    float64
 5   low                      848 non-null    float64
 6   close                    848 non-null    float64
 7   adj_close                848 non-null    float64
 8   volume                   848 non-null    int64
 9   type                     848 non-null    object
 10  ema_adj_close_200p       649 non-null    float32
 11  ema_adj_close_200p_diff  649 non-null    float32
 12  ema_close_200p           649 non-null    float32
 13  ema_close_200p_diff      649 non-null    float32
 14  rsi                      408 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 86.3+ KB
Ticker: CCME11.SA - Shape (212, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              212 non-null    object
 1   open_time                212 non-null    int64
 2   ticker                   212 non-null    object
 3   open                     212 non-null    float64
 4   high                     212 non-null    float64
 5   low                      212 non-null    float64
 6   close                    212 non-null    float64
 7   adj_close                212 non-null    float64
 8   volume                   212 non-null    int64
 9   type                     212 non-null    object
 10  ema_adj_close_200p       13 non-null     float32
 11  ema_adj_close_200p_diff  13 non-null     float32
 12  ema_close_200p           13 non-null     float32
 13  ema_close_200p_diff      13 non-null     float32
 14  rsi                      198 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 21.7+ KB
Ticker: JASC11.SA - Shape (320, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              320 non-null    object
 1   open_time                320 non-null    int64
 2   ticker                   320 non-null    object
 3   open                     320 non-null    float64
 4   high                     320 non-null    float64
 5   low                      320 non-null    float64
 6   close                    320 non-null    float64
 7   adj_close                320 non-null    float64
 8   volume                   320 non-null    int64
 9   type                     320 non-null    object
 10  ema_adj_close_200p       121 non-null    float32
 11  ema_adj_close_200p_diff  121 non-null    float32
 12  ema_close_200p           121 non-null    float32
 13  ema_close_200p_diff      121 non-null    float32
 14  rsi                      304 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 32.6+ KB
Ticker: ALUP3.SA - Shape (1782, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1782 entries, 0 to 1781
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1782 non-null   object
 1   open_time                1782 non-null   int64
 2   ticker                   1782 non-null   object
 3   open                     1782 non-null   float64
 4   high                     1782 non-null   float64
 5   low                      1782 non-null   float64
 6   close                    1782 non-null   float64
 7   adj_close                1782 non-null   float64
 8   volume                   1782 non-null   int64
 9   type                     1782 non-null   object
 10  ema_adj_close_200p       1583 non-null   float32
 11  ema_adj_close_200p_diff  1583 non-null   float32
 12  ema_close_200p           1583 non-null   float32
 13  ema_close_200p_diff      1583 non-null   float32
 14  rsi                      1768 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 181.1+ KB
Ticker: SNCI11.SA - Shape (448, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              448 non-null    object
 1   open_time                448 non-null    int64
 2   ticker                   448 non-null    object
 3   open                     448 non-null    float64
 4   high                     448 non-null    float64
 5   low                      448 non-null    float64
 6   close                    448 non-null    float64
 7   adj_close                448 non-null    float64
 8   volume                   448 non-null    int64
 9   type                     448 non-null    object
 10  ema_adj_close_200p       249 non-null    float32
 11  ema_adj_close_200p_diff  249 non-null    float32
 12  ema_close_200p           249 non-null    float32
 13  ema_close_200p_diff      249 non-null    float32
 14  rsi                      434 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 45.6+ KB
Ticker: SAPR3.SA - Shape (5017, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5017 entries, 0 to 5016
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5017 non-null   object
 1   open_time                5017 non-null   int64
 2   ticker                   5017 non-null   object
 3   open                     5017 non-null   float64
 4   high                     5017 non-null   float64
 5   low                      5017 non-null   float64
 6   close                    5017 non-null   float64
 7   adj_close                5017 non-null   float64
 8   volume                   5017 non-null   int64
 9   type                     5017 non-null   object
 10  ema_adj_close_200p       4818 non-null   float32
 11  ema_adj_close_200p_diff  4818 non-null   float32
 12  ema_close_200p           4818 non-null   float32
 13  ema_close_200p_diff      4818 non-null   float32
 14  rsi                      5003 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 509.7+ KB
Ticker: JURO11.SA - Shape (486, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              486 non-null    object
 1   open_time                486 non-null    int64
 2   ticker                   486 non-null    object
 3   open                     486 non-null    float64
 4   high                     486 non-null    float64
 5   low                      486 non-null    float64
 6   close                    486 non-null    float64
 7   adj_close                486 non-null    float64
 8   volume                   486 non-null    int64
 9   type                     486 non-null    object
 10  ema_adj_close_200p       287 non-null    float32
 11  ema_adj_close_200p_diff  287 non-null    float32
 12  ema_close_200p           287 non-null    float32
 13  ema_close_200p_diff      287 non-null    float32
 14  rsi                      472 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 49.5+ KB
Ticker: GGPS3.SA - Shape (649, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              649 non-null    object
 1   open_time                649 non-null    int64
 2   ticker                   649 non-null    object
 3   open                     649 non-null    float64
 4   high                     649 non-null    float64
 5   low                      649 non-null    float64
 6   close                    649 non-null    float64
 7   adj_close                649 non-null    float64
 8   volume                   649 non-null    int64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: HGRU11.SA - Shape (1325, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325 entries, 0 to 1324
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1325 non-null   object
 1   open_time                1325 non-null   int64
 2   ticker                   1325 non-null   object
 3   open                     1325 non-null   float64
 4   high                     1325 non-null   float64
 5   low                      1325 non-null   float64
 6   close                    1325 non-null   float64
 7   adj_close                1325 non-null   float64
 8   volume                   1325 non-null   int64
 9   type                     1325 non-null   object
 10  ema_adj_close_200p       1126 non-null   float32
 11  ema_adj_close_200p_diff  1126 non-null   float32
 12  ema_close_200p           1126 non-null   float32
 13  ema_close_200p_diff      1126 non-null   float32
 14  rsi                      1311 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 134.7+ KB
Ticker: BBFI11B.SA - Shape (3282, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3282 non-null   object
 1   open_time                3282 non-null   int64
 2   ticker                   3282 non-null   object
 3   open                     3282 non-null   float64
 4   high                     3282 non-null   float64
 5   low                      3282 non-null   float64
 6   close                    3282 non-null   float64
 7   adj_close                3282 non-null   float64
 8   volume                   3282 non-null   int64
 9   type                     3282 non-null   object
 10  ema_adj_close_200p       3083 non-null   float32
 11  ema_adj_close_200p_diff  3083 non-null   float32
 12  ema_close_200p           3083 non-null   float32
 13  ema_close_200p_diff      3083 non-null   float32
 14  rsi                      3268 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 333.5+ KB
Ticker: FATN11.SA - Shape (430, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              430 non-null    object
 1   open_time                430 non-null    int64
 2   ticker                   430 non-null    object
 3   open                     430 non-null    float64
 4   high                     430 non-null    float64
 5   low                      430 non-null    float64
 6   close                    430 non-null    float64
 7   adj_close                430 non-null    float64
 8   volume                   430 non-null    int64
 9   type                     430 non-null    object
 10  ema_adj_close_200p       231 non-null    float32
 11  ema_adj_close_200p_diff  231 non-null    float32
 12  ema_close_200p           231 non-null    float32
 13  ema_close_200p_diff      231 non-null    float32
 14  rsi                      416 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 43.8+ KB
Ticker: GOLL4.SA - Shape (4839, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4839 entries, 0 to 4838
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4839 non-null   object
 1   open_time                4839 non-null   int64
 2   ticker                   4839 non-null   object
 3   open                     4839 non-null   float64
 4   high                     4839 non-null   float64
 5   low                      4839 non-null   float64
 6   close                    4839 non-null   float64
 7   adj_close                4839 non-null   float64
 8   volume                   4839 non-null   int64
 9   type                     4839 non-null   object
 10  ema_adj_close_200p       4640 non-null   float32
 11  ema_adj_close_200p_diff  4640 non-null   float32
 12  ema_close_200p           4640 non-null   float32
 13  ema_close_200p_diff      4640 non-null   float32
 14  rsi                      4825 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 491.6+ KB
Ticker: ORPD11.SA - Shape (506, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              506 non-null    object
 1   open_time                506 non-null    int64
 2   ticker                   506 non-null    object
 3   open                     506 non-null    float64
 4   high                     506 non-null    float64
 5   low                      506 non-null    float64
 6   close                    506 non-null    float64
 7   adj_close                506 non-null    float64
 8   volume                   506 non-null    int64
 9   type                     506 non-null    object
 10  ema_adj_close_200p       307 non-null    float32
 11  ema_adj_close_200p_diff  307 non-null    float32
 12  ema_close_200p           307 non-null    float32
 13  ema_close_200p_diff      307 non-null    float32
 14  rsi                      366 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 51.5+ KB
Ticker: HAPV3.SA - Shape (1389, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1389 non-null   object
 1   open_time                1389 non-null   int64
 2   ticker                   1389 non-null   object
 3   open                     1389 non-null   float64
 4   high                     1389 non-null   float64
 5   low                      1389 non-null   float64
 6   close                    1389 non-null   float64
 7   adj_close                1389 non-null   float64
 8   volume                   1389 non-null   int64
 9   type                     1389 non-null   object
 10  ema_adj_close_200p       1190 non-null   float32
 11  ema_adj_close_200p_diff  1190 non-null   float32
 12  ema_close_200p           1190 non-null   float32
 13  ema_close_200p_diff      1190 non-null   float32
 14  rsi                      1375 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 141.2+ KB
Ticker: BMIN3.SA - Shape (5888, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5888 entries, 0 to 5887
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5888 non-null   object
 1   open_time                5888 non-null   int64
 2   ticker                   5888 non-null   object
 3   open                     5888 non-null   float64
 4   high                     5888 non-null   float64
 5   low                      5888 non-null   float64
 6   close                    5888 non-null   float64
 7   adj_close                5888 non-null   float64
 8   volume                   5888 non-null   int64
 9   type                     5888 non-null   object
 10  ema_adj_close_200p       5689 non-null   float32
 11  ema_adj_close_200p_diff  5689 non-null   float32
 12  ema_close_200p           5689 non-null   float32
 13  ema_close_200p_diff      5689 non-null   float32
 14  rsi                      5874 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 598.1+ KB
Ticker: WLMM4.SA - Shape (6006, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6006 entries, 0 to 6005
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6006 non-null   object
 1   open_time                6006 non-null   int64
 2   ticker                   6006 non-null   object
 3   open                     6006 non-null   float64
 4   high                     6006 non-null   float64
 5   low                      6006 non-null   float64
 6   close                    6006 non-null   float64
 7   adj_close                6006 non-null   float64
 8   volume                   6006 non-null   int64
 9   type                     6006 non-null   object
 10  ema_adj_close_200p       5807 non-null   float32
 11  ema_adj_close_200p_diff  5807 non-null   float32
 12  ema_close_200p           5807 non-null   float32
 13  ema_close_200p_diff      5807 non-null   float32
 14  rsi                      5992 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.1+ KB
Ticker: RBGS11.SA - Shape (2317, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2317 entries, 0 to 2316
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2317 non-null   object
 1   open_time                2317 non-null   int64
 2   ticker                   2317 non-null   object
 3   open                     2317 non-null   float64
 4   high                     2317 non-null   float64
 5   low                      2317 non-null   float64
 6   close                    2317 non-null   float64
 7   adj_close                2317 non-null   float64
 8   volume                   2317 non-null   int64
 9   type                     2317 non-null   object
 10  ema_adj_close_200p       2118 non-null   float32
 11  ema_adj_close_200p_diff  2118 non-null   float32
 12  ema_close_200p           2118 non-null   float32
 13  ema_close_200p_diff      2118 non-null   float32
 14  rsi                      2303 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.4+ KB
Ticker: TRPL4.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: PATI3.SA - Shape (5989, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5989 entries, 0 to 5988
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5989 non-null   object
 1   open_time                5989 non-null   int64
 2   ticker                   5989 non-null   object
 3   open                     5989 non-null   float64
 4   high                     5989 non-null   float64
 5   low                      5989 non-null   float64
 6   close                    5989 non-null   float64
 7   adj_close                5989 non-null   float64
 8   volume                   5989 non-null   int64
 9   type                     5989 non-null   object
 10  ema_adj_close_200p       5790 non-null   float32
 11  ema_adj_close_200p_diff  5790 non-null   float32
 12  ema_close_200p           5790 non-null   float32
 13  ema_close_200p_diff      5790 non-null   float32
 14  rsi                      5975 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 608.4+ KB
Ticker: PLPL3.SA - Shape (795, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 795 entries, 0 to 794
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              795 non-null    object
 1   open_time                795 non-null    int64
 2   ticker                   795 non-null    object
 3   open                     795 non-null    float64
 4   high                     795 non-null    float64
 5   low                      795 non-null    float64
 6   close                    795 non-null    float64
 7   adj_close                795 non-null    float64
 8   volume                   795 non-null    int64
 9   type                     795 non-null    object
 10  ema_adj_close_200p       596 non-null    float32
 11  ema_adj_close_200p_diff  596 non-null    float32
 12  ema_close_200p           596 non-null    float32
 13  ema_close_200p_diff      596 non-null    float32
 14  rsi                      781 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 80.9+ KB
Ticker: EVEN3.SA - Shape (4135, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4135 entries, 0 to 4134
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4135 non-null   object
 1   open_time                4135 non-null   int64
 2   ticker                   4135 non-null   object
 3   open                     4135 non-null   float64
 4   high                     4135 non-null   float64
 5   low                      4135 non-null   float64
 6   close                    4135 non-null   float64
 7   adj_close                4135 non-null   float64
 8   volume                   4135 non-null   int64
 9   type                     4135 non-null   object
 10  ema_adj_close_200p       3936 non-null   float32
 11  ema_adj_close_200p_diff  3936 non-null   float32
 12  ema_close_200p           3936 non-null   float32
 13  ema_close_200p_diff      3936 non-null   float32
 14  rsi                      4121 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 420.1+ KB
Ticker: CEBR6.SA - Shape (3952, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3952 entries, 0 to 3951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3952 non-null   object
 1   open_time                3952 non-null   int64
 2   ticker                   3952 non-null   object
 3   open                     3952 non-null   float64
 4   high                     3952 non-null   float64
 5   low                      3952 non-null   float64
 6   close                    3952 non-null   float64
 7   adj_close                3952 non-null   float64
 8   volume                   3952 non-null   int64
 9   type                     3952 non-null   object
 10  ema_adj_close_200p       3753 non-null   float32
 11  ema_adj_close_200p_diff  3753 non-null   float32
 12  ema_close_200p           3753 non-null   float32
 13  ema_close_200p_diff      3753 non-null   float32
 14  rsi                      3938 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.5+ KB
Ticker: NAVT11.SA - Shape (533, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              533 non-null    object
 1   open_time                533 non-null    int64
 2   ticker                   533 non-null    object
 3   open                     533 non-null    float64
 4   high                     533 non-null    float64
 5   low                      533 non-null    float64
 6   close                    533 non-null    float64
 7   adj_close                533 non-null    float64
 8   volume                   533 non-null    int64
 9   type                     533 non-null    object
 10  ema_adj_close_200p       334 non-null    float32
 11  ema_adj_close_200p_diff  334 non-null    float32
 12  ema_close_200p           334 non-null    float32
 13  ema_close_200p_diff      334 non-null    float32
 14  rsi                      519 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 54.3+ KB
Ticker: PGMN3.SA - Shape (805, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805 entries, 0 to 804
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              805 non-null    object
 1   open_time                805 non-null    int64
 2   ticker                   805 non-null    object
 3   open                     805 non-null    float64
 4   high                     805 non-null    float64
 5   low                      805 non-null    float64
 6   close                    805 non-null    float64
 7   adj_close                805 non-null    float64
 8   volume                   805 non-null    int64
 9   type                     805 non-null    object
 10  ema_adj_close_200p       606 non-null    float32
 11  ema_adj_close_200p_diff  606 non-null    float32
 12  ema_close_200p           606 non-null    float32
 13  ema_close_200p_diff      606 non-null    float32
 14  rsi                      791 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 81.9+ KB
Ticker: ENJU3.SA - Shape (761, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              761 non-null    object
 1   open_time                761 non-null    int64
 2   ticker                   761 non-null    object
 3   open                     761 non-null    float64
 4   high                     761 non-null    float64
 5   low                      761 non-null    float64
 6   close                    761 non-null    float64
 7   adj_close                761 non-null    float64
 8   volume                   761 non-null    int64
 9   type                     761 non-null    object
 10  ema_adj_close_200p       562 non-null    float32
 11  ema_adj_close_200p_diff  562 non-null    float32
 12  ema_close_200p           562 non-null    float32
 13  ema_close_200p_diff      562 non-null    float32
 14  rsi                      747 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 77.4+ KB
Ticker: WEGE3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: PMAM3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: RPAD3.SA - Shape (6002, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6002 entries, 0 to 6001
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6002 non-null   object
 1   open_time                6002 non-null   int64
 2   ticker                   6002 non-null   object
 3   open                     6002 non-null   float64
 4   high                     6002 non-null   float64
 5   low                      6002 non-null   float64
 6   close                    6002 non-null   float64
 7   adj_close                6002 non-null   float64
 8   volume                   6002 non-null   int64
 9   type                     6002 non-null   object
 10  ema_adj_close_200p       5803 non-null   float32
 11  ema_adj_close_200p_diff  5803 non-null   float32
 12  ema_close_200p           5803 non-null   float32
 13  ema_close_200p_diff      5803 non-null   float32
 14  rsi                      5988 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.7+ KB
Ticker: EDFO11B.SA - Shape (2317, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2317 entries, 0 to 2316
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2317 non-null   object
 1   open_time                2317 non-null   int64
 2   ticker                   2317 non-null   object
 3   open                     2317 non-null   float64
 4   high                     2317 non-null   float64
 5   low                      2317 non-null   float64
 6   close                    2317 non-null   float64
 7   adj_close                2317 non-null   float64
 8   volume                   2317 non-null   int64
 9   type                     2317 non-null   object
 10  ema_adj_close_200p       2118 non-null   float32
 11  ema_adj_close_200p_diff  2118 non-null   float32
 12  ema_close_200p           2118 non-null   float32
 13  ema_close_200p_diff      2118 non-null   float32
 14  rsi                      2303 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.4+ KB
Ticker: RBTS11.SA - Shape (905, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 905 entries, 0 to 904
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              905 non-null    object
 1   open_time                905 non-null    int64
 2   ticker                   905 non-null    object
 3   open                     905 non-null    float64
 4   high                     905 non-null    float64
 5   low                      905 non-null    float64
 6   close                    905 non-null    float64
 7   adj_close                905 non-null    float64
 8   volume                   905 non-null    int64
 9   type                     905 non-null    object
 10  ema_adj_close_200p       706 non-null    float32
 11  ema_adj_close_200p_diff  706 non-null    float32
 12  ema_close_200p           706 non-null    float32
 13  ema_close_200p_diff      706 non-null    float32
 14  rsi                      298 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 92.0+ KB
Ticker: VSPT3.SA - Shape (3413, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3413 entries, 0 to 3412
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3413 non-null   object
 1   open_time                3413 non-null   int64
 2   ticker                   3413 non-null   object
 3   open                     3413 non-null   float64
 4   high                     3413 non-null   float64
 5   low                      3413 non-null   float64
 6   close                    3413 non-null   float64
 7   adj_close                3413 non-null   float64
 8   volume                   3413 non-null   int64
 9   type                     3413 non-null   object
 10  ema_adj_close_200p       3214 non-null   float32
 11  ema_adj_close_200p_diff  3214 non-null   float32
 12  ema_close_200p           3214 non-null   float32
 13  ema_close_200p_diff      3214 non-null   float32
 14  rsi                      3377 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 346.8+ KB
Ticker: RBRY11.SA - Shape (1127, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127 entries, 0 to 1126
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1127 non-null   object
 1   open_time                1127 non-null   int64
 2   ticker                   1127 non-null   object
 3   open                     1127 non-null   float64
 4   high                     1127 non-null   float64
 5   low                      1127 non-null   float64
 6   close                    1127 non-null   float64
 7   adj_close                1127 non-null   float64
 8   volume                   1127 non-null   int64
 9   type                     1127 non-null   object
 10  ema_adj_close_200p       928 non-null    float32
 11  ema_adj_close_200p_diff  928 non-null    float32
 12  ema_close_200p           928 non-null    float32
 13  ema_close_200p_diff      928 non-null    float32
 14  rsi                      1113 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 114.6+ KB
Ticker: VCRA11.SA - Shape (355, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355 entries, 0 to 354
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              355 non-null    object
 1   open_time                355 non-null    int64
 2   ticker                   355 non-null    object
 3   open                     355 non-null    float64
 4   high                     355 non-null    float64
 5   low                      355 non-null    float64
 6   close                    355 non-null    float64
 7   adj_close                355 non-null    float64
 8   volume                   355 non-null    int64
 9   type                     355 non-null    object
 10  ema_adj_close_200p       156 non-null    float32
 11  ema_adj_close_200p_diff  156 non-null    float32
 12  ema_close_200p           156 non-null    float32
 13  ema_close_200p_diff      156 non-null    float32
 14  rsi                      341 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 36.2+ KB
Ticker: GCFF11.SA - Shape (360, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              360 non-null    object
 1   open_time                360 non-null    int64
 2   ticker                   360 non-null    object
 3   open                     360 non-null    float64
 4   high                     360 non-null    float64
 5   low                      360 non-null    float64
 6   close                    360 non-null    float64
 7   adj_close                360 non-null    float64
 8   volume                   360 non-null    int64
 9   type                     360 non-null    object
 10  ema_adj_close_200p       161 non-null    float32
 11  ema_adj_close_200p_diff  161 non-null    float32
 12  ema_close_200p           161 non-null    float32
 13  ema_close_200p_diff      161 non-null    float32
 14  rsi                      346 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 36.7+ KB
Ticker: PICE11.SA - Shape (681, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              681 non-null    object
 1   open_time                681 non-null    int64
 2   ticker                   681 non-null    object
 3   open                     681 non-null    float64
 4   high                     681 non-null    float64
 5   low                      681 non-null    float64
 6   close                    681 non-null    float64
 7   adj_close                681 non-null    float64
 8   volume                   681 non-null    int64
 9   type                     681 non-null    object
 10  ema_adj_close_200p       482 non-null    float32
 11  ema_adj_close_200p_diff  482 non-null    float32
 12  ema_close_200p           482 non-null    float32
 13  ema_close_200p_diff      482 non-null    float32
 14  rsi                      667 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 69.3+ KB
Ticker: NEWU11.SA - Shape (854, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 854 entries, 0 to 853
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              854 non-null    object
 1   open_time                854 non-null    int64
 2   ticker                   854 non-null    object
 3   open                     854 non-null    float64
 4   high                     854 non-null    float64
 5   low                      854 non-null    float64
 6   close                    854 non-null    float64
 7   adj_close                854 non-null    float64
 8   volume                   854 non-null    int64
 9   type                     854 non-null    object
 10  ema_adj_close_200p       655 non-null    float32
 11  ema_adj_close_200p_diff  655 non-null    float32
 12  ema_close_200p           655 non-null    float32
 13  ema_close_200p_diff      655 non-null    float32
 14  rsi                      840 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 86.9+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: VVRI11.SA - Shape (145, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              145 non-null    object
 1   open_time                145 non-null    int64
 2   ticker                   145 non-null    object
 3   open                     145 non-null    float64
 4   high                     145 non-null    float64
 5   low                      145 non-null    float64
 6   close                    145 non-null    float64
 7   adj_close                145 non-null    float64
 8   volume                   145 non-null    int64
 9   type                     145 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      131 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 17.1+ KB
Ticker: MOVI3.SA - Shape (1626, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1626 entries, 0 to 1625
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1626 non-null   object
 1   open_time                1626 non-null   int64
 2   ticker                   1626 non-null   object
 3   open                     1626 non-null   float64
 4   high                     1626 non-null   float64
 5   low                      1626 non-null   float64
 6   close                    1626 non-null   float64
 7   adj_close                1626 non-null   float64
 8   volume                   1626 non-null   int64
 9   type                     1626 non-null   object
 10  ema_adj_close_200p       1427 non-null   float32
 11  ema_adj_close_200p_diff  1427 non-null   float32
 12  ema_close_200p           1427 non-null   float32
 13  ema_close_200p_diff      1427 non-null   float32
 14  rsi                      1612 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 165.3+ KB
Ticker: GOAU4.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: SNSY3.SA - Shape (4163, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4163 entries, 0 to 4162
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4163 non-null   object
 1   open_time                4163 non-null   int64
 2   ticker                   4163 non-null   object
 3   open                     4163 non-null   float64
 4   high                     4163 non-null   float64
 5   low                      4163 non-null   float64
 6   close                    4163 non-null   float64
 7   adj_close                4163 non-null   float64
 8   volume                   4163 non-null   int64
 9   type                     4163 non-null   object
 10  ema_adj_close_200p       3964 non-null   float32
 11  ema_adj_close_200p_diff  3964 non-null   float32
 12  ema_close_200p           3964 non-null   float32
 13  ema_close_200p_diff      3964 non-null   float32
 14  rsi                      3966 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 422.9+ KB
Ticker: REIT11.SA - Shape (223, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              223 non-null    object
 1   open_time                223 non-null    int64
 2   ticker                   223 non-null    object
 3   open                     223 non-null    float64
 4   high                     223 non-null    float64
 5   low                      223 non-null    float64
 6   close                    223 non-null    float64
 7   adj_close                223 non-null    float64
 8   volume                   223 non-null    int64
 9   type                     223 non-null    object
 10  ema_adj_close_200p       24 non-null     float32
 11  ema_adj_close_200p_diff  24 non-null     float32
 12  ema_close_200p           24 non-null     float32
 13  ema_close_200p_diff      24 non-null     float32
 14  rsi                      209 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 22.8+ KB
Ticker: RSUL4.SA - Shape (6005, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6005 entries, 0 to 6004
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6005 non-null   object
 1   open_time                6005 non-null   int64
 2   ticker                   6005 non-null   object
 3   open                     6005 non-null   float64
 4   high                     6005 non-null   float64
 5   low                      6005 non-null   float64
 6   close                    6005 non-null   float64
 7   adj_close                6005 non-null   float64
 8   volume                   6005 non-null   int64
 9   type                     6005 non-null   object
 10  ema_adj_close_200p       5806 non-null   float32
 11  ema_adj_close_200p_diff  5806 non-null   float32
 12  ema_close_200p           5806 non-null   float32
 13  ema_close_200p_diff      5806 non-null   float32
 14  rsi                      5991 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.0+ KB
Ticker: BPRP11.SA - Shape (939, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              939 non-null    object
 1   open_time                939 non-null    int64
 2   ticker                   939 non-null    object
 3   open                     939 non-null    float64
 4   high                     939 non-null    float64
 5   low                      939 non-null    float64
 6   close                    939 non-null    float64
 7   adj_close                939 non-null    float64
 8   volume                   939 non-null    int64
 9   type                     939 non-null    object
 10  ema_adj_close_200p       740 non-null    float32
 11  ema_adj_close_200p_diff  740 non-null    float32
 12  ema_close_200p           740 non-null    float32
 13  ema_close_200p_diff      740 non-null    float32
 14  rsi                      925 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.5+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
index 14 is out of bounds for axis 0 with size 1
Ticker: IGBR3.SA - Shape (1, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1 non-null      object
 1   open_time                1 non-null      int64
 2   ticker                   1 non-null      object
 3   open                     1 non-null      float64
 4   high                     1 non-null      float64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: BPAN4.SA - Shape (3978, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3978 entries, 0 to 3977
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3978 non-null   object
 1   open_time                3978 non-null   int64
 2   ticker                   3978 non-null   object
 3   open                     3978 non-null   float64
 4   high                     3978 non-null   float64
 5   low                      3978 non-null   float64
 6   close                    3978 non-null   float64
 7   adj_close                3978 non-null   float64
 8   volume                   3978 non-null   int64
 9   type                     3978 non-null   object
 10  ema_adj_close_200p       3779 non-null   float32
 11  ema_adj_close_200p_diff  3779 non-null   float32
 12  ema_close_200p           3779 non-null   float32
 13  ema_close_200p_diff      3779 non-null   float32
 14  rsi                      3964 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 404.1+ KB
Ticker: PEMA11.SA - Shape (529, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529 entries, 0 to 528
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              529 non-null    object
 1   open_time                529 non-null    int64
 2   ticker                   529 non-null    object
 3   open                     529 non-null    float64
 4   high                     529 non-null    float64
 5   low                      529 non-null    float64
 6   close                    529 non-null    float64
 7   adj_close                529 non-null    float64
 8   volume                   529 non-null    int64
 9   type                     529 non-null    object
 10  ema_adj_close_200p       330 non-null    float32
 11  ema_adj_close_200p_diff  330 non-null    float32
 12  ema_close_200p           330 non-null    float32
 13  ema_close_200p_diff      330 non-null    float32
 14  rsi                      514 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 53.9+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: JCCJ11.SA - Shape (44, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              44 non-null     object
 1   open_time                44 non-null     int64
 2   ticker                   44 non-null     object
 3   open                     44 non-null     float64
 4   high                     44 non-null     float64
 5   low                      44 non-null     float64
 6   close                    44 non-null     float64
 7   adj_close                44 non-null     float64
 8   volume                   44 non-null     int64
 9   type                     44 non-null     object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      30 non-null     float64
dtypes: float64(6), int64(2), object(7)
memory usage: 5.3+ KB
Ticker: BRKM6.SA - Shape (5309, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5309 entries, 0 to 5308
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5309 non-null   object
 1   open_time                5309 non-null   int64
 2   ticker                   5309 non-null   object
 3   open                     5309 non-null   float64
 4   high                     5309 non-null   float64
 5   low                      5309 non-null   float64
 6   close                    5309 non-null   float64
 7   adj_close                5309 non-null   float64
 8   volume                   5309 non-null   int64
 9   type                     5309 non-null   object
 10  ema_adj_close_200p       5110 non-null   float32
 11  ema_adj_close_200p_diff  5110 non-null   float32
 12  ema_close_200p           5110 non-null   float32
 13  ema_close_200p_diff      5110 non-null   float32
 14  rsi                      5295 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 539.3+ KB
Ticker: XPIE11.SA - Shape (1054, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1054 non-null   object
 1   open_time                1054 non-null   int64
 2   ticker                   1054 non-null   object
 3   open                     1054 non-null   float64
 4   high                     1054 non-null   float64
 5   low                      1054 non-null   float64
 6   close                    1054 non-null   float64
 7   adj_close                1054 non-null   float64
 8   volume                   1054 non-null   int64
 9   type                     1054 non-null   object
 10  ema_adj_close_200p       855 non-null    float32
 11  ema_adj_close_200p_diff  855 non-null    float32
 12  ema_close_200p           855 non-null    float32
 13  ema_close_200p_diff      855 non-null    float32
 14  rsi                      1040 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 107.2+ KB
Ticker: DEXP3.SA - Shape (5948, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5948 entries, 0 to 5947
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5948 non-null   object
 1   open_time                5948 non-null   int64
 2   ticker                   5948 non-null   object
 3   open                     5948 non-null   float64
 4   high                     5948 non-null   float64
 5   low                      5948 non-null   float64
 6   close                    5948 non-null   float64
 7   adj_close                5948 non-null   float64
 8   volume                   5948 non-null   int64
 9   type                     5948 non-null   object
 10  ema_adj_close_200p       5749 non-null   float32
 11  ema_adj_close_200p_diff  5749 non-null   float32
 12  ema_close_200p           5749 non-null   float32
 13  ema_close_200p_diff      5749 non-null   float32
 14  rsi                      5934 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 604.2+ KB
Ticker: AHEB3.SA - Shape (5999, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5999 entries, 0 to 5998
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5999 non-null   object
 1   open_time                5999 non-null   int64
 2   ticker                   5999 non-null   object
 3   open                     5999 non-null   float64
 4   high                     5999 non-null   float64
 5   low                      5999 non-null   float64
 6   close                    5999 non-null   float64
 7   adj_close                5999 non-null   float64
 8   volume                   5999 non-null   int64
 9   type                     5999 non-null   object
 10  ema_adj_close_200p       5800 non-null   float32
 11  ema_adj_close_200p_diff  5800 non-null   float32
 12  ema_close_200p           5800 non-null   float32
 13  ema_close_200p_diff      5800 non-null   float32
 14  rsi                      5969 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 609.4+ KB
Ticker: VIVT3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: XPIN11.SA - Shape (869, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 869 entries, 0 to 868
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              869 non-null    object
 1   open_time                869 non-null    int64
 2   ticker                   869 non-null    object
 3   open                     869 non-null    float64
 4   high                     869 non-null    float64
 5   low                      869 non-null    float64
 6   close                    869 non-null    float64
 7   adj_close                869 non-null    float64
 8   volume                   869 non-null    int64
 9   type                     869 non-null    object
 10  ema_adj_close_200p       670 non-null    float32
 11  ema_adj_close_200p_diff  670 non-null    float32
 12  ema_close_200p           670 non-null    float32
 13  ema_close_200p_diff      670 non-null    float32
 14  rsi                      855 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 88.4+ KB
Ticker: KNSC11.SA - Shape (446, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446 entries, 0 to 445
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              446 non-null    object
 1   open_time                446 non-null    int64
 2   ticker                   446 non-null    object
 3   open                     446 non-null    float64
 4   high                     446 non-null    float64
 5   low                      446 non-null    float64
 6   close                    446 non-null    float64
 7   adj_close                446 non-null    float64
 8   volume                   446 non-null    int64
 9   type                     446 non-null    object
 10  ema_adj_close_200p       247 non-null    float32
 11  ema_adj_close_200p_diff  247 non-null    float32
 12  ema_close_200p           247 non-null    float32
 13  ema_close_200p_diff      247 non-null    float32
 14  rsi                      432 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 45.4+ KB
Ticker: GESE11B.SA - Shape (787, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 787 entries, 0 to 786
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              787 non-null    object
 1   open_time                787 non-null    int64
 2   ticker                   787 non-null    object
 3   open                     787 non-null    float64
 4   high                     787 non-null    float64
 5   low                      787 non-null    float64
 6   close                    787 non-null    float64
 7   adj_close                787 non-null    float64
 8   volume                   787 non-null    int64
 9   type                     787 non-null    object
 10  ema_adj_close_200p       588 non-null    float32
 11  ema_adj_close_200p_diff  588 non-null    float32
 12  ema_close_200p           588 non-null    float32
 13  ema_close_200p_diff      588 non-null    float32
 14  rsi                      415 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 80.1+ KB
Ticker: SOND6.SA - Shape (3944, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3944 entries, 0 to 3943
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3944 non-null   object
 1   open_time                3944 non-null   int64
 2   ticker                   3944 non-null   object
 3   open                     3944 non-null   float64
 4   high                     3944 non-null   float64
 5   low                      3944 non-null   float64
 6   close                    3944 non-null   float64
 7   adj_close                3944 non-null   float64
 8   volume                   3944 non-null   int64
 9   type                     3944 non-null   object
 10  ema_adj_close_200p       3745 non-null   float32
 11  ema_adj_close_200p_diff  3745 non-null   float32
 12  ema_close_200p           3745 non-null   float32
 13  ema_close_200p_diff      3745 non-null   float32
 14  rsi                      3930 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 400.7+ KB
Ticker: CEEB3.SA - Shape (6005, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6005 entries, 0 to 6004
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6005 non-null   object
 1   open_time                6005 non-null   int64
 2   ticker                   6005 non-null   object
 3   open                     6005 non-null   float64
 4   high                     6005 non-null   float64
 5   low                      6005 non-null   float64
 6   close                    6005 non-null   float64
 7   adj_close                6005 non-null   float64
 8   volume                   6005 non-null   int64
 9   type                     6005 non-null   object
 10  ema_adj_close_200p       5806 non-null   float32
 11  ema_adj_close_200p_diff  5806 non-null   float32
 12  ema_close_200p           5806 non-null   float32
 13  ema_close_200p_diff      5806 non-null   float32
 14  rsi                      5988 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.0+ KB
Ticker: HGIC11.SA - Shape (626, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              626 non-null    object
 1   open_time                626 non-null    int64
 2   ticker                   626 non-null    object
 3   open                     626 non-null    float64
 4   high                     626 non-null    float64
 5   low                      626 non-null    float64
 6   close                    626 non-null    float64
 7   adj_close                626 non-null    float64
 8   volume                   626 non-null    int64
 9   type                     626 non-null    object
 10  ema_adj_close_200p       427 non-null    float32
 11  ema_adj_close_200p_diff  427 non-null    float32
 12  ema_close_200p           427 non-null    float32
 13  ema_close_200p_diff      427 non-null    float32
 14  rsi                      612 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 63.7+ KB
Ticker: TELB3.SA - Shape (6006, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6006 entries, 0 to 6005
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6006 non-null   object
 1   open_time                6006 non-null   int64
 2   ticker                   6006 non-null   object
 3   open                     6006 non-null   float64
 4   high                     6006 non-null   float64
 5   low                      6006 non-null   float64
 6   close                    6006 non-null   float64
 7   adj_close                6006 non-null   float64
 8   volume                   6006 non-null   int64
 9   type                     6006 non-null   object
 10  ema_adj_close_200p       5807 non-null   float32
 11  ema_adj_close_200p_diff  5807 non-null   float32
 12  ema_close_200p           5807 non-null   float32
 13  ema_close_200p_diff      5807 non-null   float32
 14  rsi                      5992 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.1+ KB
Ticker: SNID11.SA - Shape (202, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              202 non-null    object
 1   open_time                202 non-null    int64
 2   ticker                   202 non-null    object
 3   open                     202 non-null    float64
 4   high                     202 non-null    float64
 5   low                      202 non-null    float64
 6   close                    202 non-null    float64
 7   adj_close                202 non-null    float64
 8   volume                   202 non-null    int64
 9   type                     202 non-null    object
 10  ema_adj_close_200p       3 non-null      float32
 11  ema_adj_close_200p_diff  3 non-null      float32
 12  ema_close_200p           3 non-null      float32
 13  ema_close_200p_diff      3 non-null      float32
 14  rsi                      188 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 20.6+ KB
Ticker: DVFF11.SA - Shape (431, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              431 non-null    object
 1   open_time                431 non-null    int64
 2   ticker                   431 non-null    object
 3   open                     431 non-null    float64
 4   high                     431 non-null    float64
 5   low                      431 non-null    float64
 6   close                    431 non-null    float64
 7   adj_close                431 non-null    float64
 8   volume                   431 non-null    int64
 9   type                     431 non-null    object
 10  ema_adj_close_200p       232 non-null    float32
 11  ema_adj_close_200p_diff  232 non-null    float32
 12  ema_close_200p           232 non-null    float32
 13  ema_close_200p_diff      232 non-null    float32
 14  rsi                      417 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 43.9+ KB
Ticker: XPPR11.SA - Shape (941, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              941 non-null    object
 1   open_time                941 non-null    int64
 2   ticker                   941 non-null    object
 3   open                     941 non-null    float64
 4   high                     941 non-null    float64
 5   low                      941 non-null    float64
 6   close                    941 non-null    float64
 7   adj_close                941 non-null    float64
 8   volume                   941 non-null    int64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: UCAS3.SA - Shape (2879, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2879 entries, 0 to 2878
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2879 non-null   object
 1   open_time                2879 non-null   int64
 2   ticker                   2879 non-null   object
 3   open                     2879 non-null   float64
 4   high                     2879 non-null   float64
 5   low                      2879 non-null   float64
 6   close                    2879 non-null   float64
 7   adj_close                2879 non-null   float64
 8   volume                   2879 non-null   int64
 9   type                     2879 non-null   object
 10  ema_adj_close_200p       2680 non-null   float32
 11  ema_adj_close_200p_diff  2680 non-null   float32
 12  ema_close_200p           2680 non-null   float32
 13  ema_close_200p_diff      2680 non-null   float32
 14  rsi                      2865 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 292.5+ KB
Ticker: PETZ3.SA - Shape (798, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              798 non-null    object
 1   open_time                798 non-null    int64
 2   ticker                   798 non-null    object
 3   open                     798 non-null    float64
 4   high                     798 non-null    float64
 5   low                      798 non-null    float64
 6   close                    798 non-null    float64
 7   adj_close                798 non-null    float64
 8   volume                   798 non-null    int64
 9   type                     798 non-null    object
 10  ema_adj_close_200p       599 non-null    float32
 11  ema_adj_close_200p_diff  599 non-null    float32
 12  ema_close_200p           599 non-null    float32
 13  ema_close_200p_diff      599 non-null    float32
 14  rsi                      784 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 81.2+ KB
Ticker: DCRA11.SA - Shape (453, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              453 non-null    object
 1   open_time                453 non-null    int64
 2   ticker                   453 non-null    object
 3   open                     453 non-null    float64
 4   high                     453 non-null    float64
 5   low                      453 non-null    float64
 6   close                    453 non-null    float64
 7   adj_close                453 non-null    float64
 8   volume                   453 non-null    int64
 9   type                     453 non-null    object
 10  ema_adj_close_200p       254 non-null    float32
 11  ema_adj_close_200p_diff  254 non-null    float32
 12  ema_close_200p           254 non-null    float32
 13  ema_close_200p_diff      254 non-null    float32
 14  rsi                      439 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 46.1+ KB
Ticker: BRSR5.SA - Shape (4691, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4691 entries, 0 to 4690
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4691 non-null   object
 1   open_time                4691 non-null   int64
 2   ticker                   4691 non-null   object
 3   open                     4691 non-null   float64
 4   high                     4691 non-null   float64
 5   low                      4691 non-null   float64
 6   close                    4691 non-null   float64
 7   adj_close                4691 non-null   float64
 8   volume                   4691 non-null   int64
 9   type                     4691 non-null   object
 10  ema_adj_close_200p       4492 non-null   float32
 11  ema_adj_close_200p_diff  4492 non-null   float32
 12  ema_close_200p           4492 non-null   float32
 13  ema_close_200p_diff      4492 non-null   float32
 14  rsi                      4677 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 476.6+ KB
Ticker: SEQL3.SA - Shape (781, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781 entries, 0 to 780
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              781 non-null    object
 1   open_time                781 non-null    int64
 2   ticker                   781 non-null    object
 3   open                     781 non-null    float64
 4   high                     781 non-null    float64
 5   low                      781 non-null    float64
 6   close                    781 non-null    float64
 7   adj_close                781 non-null    float64
 8   volume                   781 non-null    int64
 9   type                     781 non-null    object
 10  ema_adj_close_200p       582 non-null    float32
 11  ema_adj_close_200p_diff  582 non-null    float32
 12  ema_close_200p           582 non-null    float32
 13  ema_close_200p_diff      582 non-null    float32
 14  rsi                      767 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 79.4+ KB
Ticker: JALL3.SA - Shape (702, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              702 non-null    object
 1   open_time                702 non-null    int64
 2   ticker                   702 non-null    object
 3   open                     702 non-null    float64
 4   high                     702 non-null    float64
 5   low                      702 non-null    float64
 6   close                    702 non-null    float64
 7   adj_close                702 non-null    float64
 8   volume                   702 non-null    int64
 9   type                     702 non-null    object
 10  ema_adj_close_200p       503 non-null    float32
 11  ema_adj_close_200p_diff  503 non-null    float32
 12  ema_close_200p           503 non-null    float32
 13  ema_close_200p_diff      503 non-null    float32
 14  rsi                      688 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 71.4+ KB
Ticker: TELB4.SA - Shape (3951, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3951 entries, 0 to 3950
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3951 non-null   object
 1   open_time                3951 non-null   int64
 2   ticker                   3951 non-null   object
 3   open                     3951 non-null   float64
 4   high                     3951 non-null   float64
 5   low                      3951 non-null   float64
 6   close                    3951 non-null   float64
 7   adj_close                3951 non-null   float64
 8   volume                   3951 non-null   int64
 9   type                     3951 non-null   object
 10  ema_adj_close_200p       3752 non-null   float32
 11  ema_adj_close_200p_diff  3752 non-null   float32
 12  ema_close_200p           3752 non-null   float32
 13  ema_close_200p_diff      3752 non-null   float32
 14  rsi                      3937 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.4+ KB
Ticker: AVLL3.SA - Shape (726, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 726 entries, 0 to 725
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              726 non-null    object
 1   open_time                726 non-null    int64
 2   ticker                   726 non-null    object
 3   open                     726 non-null    float64
 4   high                     726 non-null    float64
 5   low                      726 non-null    float64
 6   close                    726 non-null    float64
 7   adj_close                726 non-null    float64
 8   volume                   726 non-null    int64
 9   type                     726 non-null    object
 10  ema_adj_close_200p       527 non-null    float32
 11  ema_adj_close_200p_diff  527 non-null    float32
 12  ema_close_200p           527 non-null    float32
 13  ema_close_200p_diff      527 non-null    float32
 14  rsi                      712 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 73.9+ KB
Ticker: VGHF11.SA - Shape (683, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              683 non-null    object
 1   open_time                683 non-null    int64
 2   ticker                   683 non-null    object
 3   open                     683 non-null    float64
 4   high                     683 non-null    float64
 5   low                      683 non-null    float64
 6   close                    683 non-null    float64
 7   adj_close                683 non-null    float64
 8   volume                   683 non-null    int64
 9   type                     683 non-null    object
 10  ema_adj_close_200p       484 non-null    float32
 11  ema_adj_close_200p_diff  484 non-null    float32
 12  ema_close_200p           484 non-null    float32
 13  ema_close_200p_diff      484 non-null    float32
 14  rsi                      669 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 69.5+ KB
Ticker: SADI11.SA - Shape (869, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 869 entries, 0 to 868
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              869 non-null    object
 1   open_time                869 non-null    int64
 2   ticker                   869 non-null    object
 3   open                     869 non-null    float64
 4   high                     869 non-null    float64
 5   low                      869 non-null    float64
 6   close                    869 non-null    float64
 7   adj_close                869 non-null    float64
 8   volume                   869 non-null    int64
 9   type                     869 non-null    object
 10  ema_adj_close_200p       670 non-null    float32
 11  ema_adj_close_200p_diff  670 non-null    float32
 12  ema_close_200p           670 non-null    float32
 13  ema_close_200p_diff      670 non-null    float32
 14  rsi                      855 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 88.4+ KB
Ticker: MEGA3.SA - Shape (483, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483 entries, 0 to 482
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              483 non-null    object
 1   open_time                483 non-null    int64
 2   ticker                   483 non-null    object
 3   open                     483 non-null    float64
 4   high                     483 non-null    float64
 5   low                      483 non-null    float64
 6   close                    483 non-null    float64
 7   adj_close                483 non-null    float64
 8   volume                   483 non-null    int64
 9   type                     483 non-null    object
 10  ema_adj_close_200p       284 non-null    float32
 11  ema_adj_close_200p_diff  284 non-null    float32
 12  ema_close_200p           284 non-null    float32
 13  ema_close_200p_diff      284 non-null    float32
 14  rsi                      469 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 49.2+ KB
Ticker: KCRE11.SA - Shape (348, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              348 non-null    object
 1   open_time                348 non-null    int64
 2   ticker                   348 non-null    object
 3   open                     348 non-null    float64
 4   high                     348 non-null    float64
 5   low                      348 non-null    float64
 6   close                    348 non-null    float64
 7   adj_close                348 non-null    float64
 8   volume                   348 non-null    int64
 9   type                     348 non-null    object
 10  ema_adj_close_200p       149 non-null    float32
 11  ema_adj_close_200p_diff  149 non-null    float32
 12  ema_close_200p           149 non-null    float32
 13  ema_close_200p_diff      149 non-null    float32
 14  rsi                      334 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 35.5+ KB
Ticker: WIZC3.SA - Shape (2113, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2113 entries, 0 to 2112
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2113 non-null   object
 1   open_time                2113 non-null   int64
 2   ticker                   2113 non-null   object
 3   open                     2113 non-null   float64
 4   high                     2113 non-null   float64
 5   low                      2113 non-null   float64
 6   close                    2113 non-null   float64
 7   adj_close                2113 non-null   float64
 8   volume                   2113 non-null   int64
 9   type                     2113 non-null   object
 10  ema_adj_close_200p       1914 non-null   float32
 11  ema_adj_close_200p_diff  1914 non-null   float32
 12  ema_close_200p           1914 non-null   float32
 13  ema_close_200p_diff      1914 non-null   float32
 14  rsi                      2099 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 214.7+ KB
Ticker: CPTR11.SA - Shape (362, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              362 non-null    object
 1   open_time                362 non-null    int64
 2   ticker                   362 non-null    object
 3   open                     362 non-null    float64
 4   high                     362 non-null    float64
 5   low                      362 non-null    float64
 6   close                    362 non-null    float64
 7   adj_close                362 non-null    float64
 8   volume                   362 non-null    int64
 9   type                     362 non-null    object
 10  ema_adj_close_200p       163 non-null    float32
 11  ema_adj_close_200p_diff  163 non-null    float32
 12  ema_close_200p           163 non-null    float32
 13  ema_close_200p_diff      163 non-null    float32
 14  rsi                      348 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 36.9+ KB
Ticker: PDTC3.SA - Shape (5893, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5893 entries, 0 to 5892
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5893 non-null   object
 1   open_time                5893 non-null   int64
 2   ticker                   5893 non-null   object
 3   open                     5893 non-null   float64
 4   high                     5893 non-null   float64
 5   low                      5893 non-null   float64
 6   close                    5893 non-null   float64
 7   adj_close                5893 non-null   float64
 8   volume                   5893 non-null   int64
 9   type                     5893 non-null   object
 10  ema_adj_close_200p       5694 non-null   float32
 11  ema_adj_close_200p_diff  5694 non-null   float32
 12  ema_close_200p           5694 non-null   float32
 13  ema_close_200p_diff      5694 non-null   float32
 14  rsi                      5879 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 598.6+ KB
Ticker: EQPA7.SA - Shape (3950, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3950 entries, 0 to 3949
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3950 non-null   object
 1   open_time                3950 non-null   int64
 2   ticker                   3950 non-null   object
 3   open                     3950 non-null   float64
 4   high                     3950 non-null   float64
 5   low                      3950 non-null   float64
 6   close                    3950 non-null   float64
 7   adj_close                3950 non-null   float64
 8   volume                   3950 non-null   int64
 9   type                     3950 non-null   object
 10  ema_adj_close_200p       3751 non-null   float32
 11  ema_adj_close_200p_diff  3751 non-null   float32
 12  ema_close_200p           3751 non-null   float32
 13  ema_close_200p_diff      3751 non-null   float32
 14  rsi                      3929 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.3+ KB
Ticker: SHUL3.SA - Shape (1994, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1994 non-null   object
 1   open_time                1994 non-null   int64
 2   ticker                   1994 non-null   object
 3   open                     1994 non-null   float64
 4   high                     1994 non-null   float64
 5   low                      1994 non-null   float64
 6   close                    1994 non-null   float64
 7   adj_close                1994 non-null   float64
 8   volume                   1994 non-null   int64
 9   type                     1994 non-null   object
 10  ema_adj_close_200p       1795 non-null   float32
 11  ema_adj_close_200p_diff  1795 non-null   float32
 12  ema_close_200p           1795 non-null   float32
 13  ema_close_200p_diff      1795 non-null   float32
 14  rsi                      1889 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 202.6+ KB
Ticker: AZEV4.SA - Shape (5968, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5968 entries, 0 to 5967
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5968 non-null   object
 1   open_time                5968 non-null   int64
 2   ticker                   5968 non-null   object
 3   open                     5968 non-null   float64
 4   high                     5968 non-null   float64
 5   low                      5968 non-null   float64
 6   close                    5968 non-null   float64
 7   adj_close                5968 non-null   float64
 8   volume                   5968 non-null   int64
 9   type                     5968 non-null   object
 10  ema_adj_close_200p       5769 non-null   float32
 11  ema_adj_close_200p_diff  5769 non-null   float32

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: ATSA11.SA - Shape (971, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 971 entries, 0 to 970
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              971 non-null    object
 1   open_time                971 non-null    int64
 2   ticker                   971 non-null    object
 3   open                     971 non-null    float64
 4   high                     971 non-null    float64
 5   low                      971 non-null    float64
 6   close                    971 non-null    float64
 7   adj_close                971 non-null    float64
 8   volume                   971 non-null    int64
 9   type                     971 non-null    object
 10  ema_adj_close_200p       772 non-null    float32
 11  ema_adj_close_200p_diff  772 non-null    float32
 12  ema_close_200p           772 non-null    float32
 13  ema_close_200p_diff      772 non-null    float32
 14  rsi                      957 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 98.7+ KB
Ticker: BBFO11.SA - Shape (724, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 724 entries, 0 to 723
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              724 non-null    object
 1   open_time                724 non-null    int64
 2   ticker                   724 non-null    object
 3   open                     724 non-null    float64
 4   high                     724 non-null    float64
 5   low                      724 non-null    float64
 6   close                    724 non-null    float64
 7   adj_close                724 non-null    float64
 8   volume                   724 non-null    int64
 9   type                     724 non-null    object
 10  ema_adj_close_200p       525 non-null    float32
 11  ema_adj_close_200p_diff  525 non-null    float32
 12  ema_close_200p           525 non-null    float32
 13  ema_close_200p_diff      525 non-null    float32
 14  rsi                      710 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 73.7+ KB
Ticker: CXSE3.SA - Shape (647, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 647 entries, 0 to 646
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              647 non-null    object
 1   open_time                647 non-null    int64
 2   ticker                   647 non-null    object
 3   open                     647 non-null    float64
 4   high                     647 non-null    float64
 5   low                      647 non-null    float64
 6   close                    647 non-null    float64
 7   adj_close                647 non-null    float64
 8   volume                   647 non-null    int64
 9   type                     647 non-null    object
 10  ema_adj_close_200p       448 non-null    float32
 11  ema_adj_close_200p_diff  448 non-null    float32
 12  ema_close_200p           448 non-null    float32
 13  ema_close_200p_diff      448 non-null    float32
 14  rsi                      633 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 65.8+ KB
Ticker: ODER4.SA - Shape (1546, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1546 entries, 0 to 1545
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1546 non-null   object
 1   open_time                1546 non-null   int64
 2   ticker                   1546 non-null   object
 3   open                     1546 non-null   float64
 4   high                     1546 non-null   float64
 5   low                      1546 non-null   float64
 6   close                    1546 non-null   float64
 7   adj_close                1546 non-null   float64
 8   volume                   1546 non-null   int64
 9   type                     1546 non-null   object
 10  ema_adj_close_200p       1347 non-null   float32
 11  ema_adj_close_200p_diff  1347 non-null   float32
 12  ema_close_200p           1347 non-null   float32
 13  ema_close_200p_diff      1347 non-null   float32
 14  rsi                      1509 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 157.1+ KB
Ticker: VBBR3.SA - Shape (1419, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1419 entries, 0 to 1418
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1419 non-null   object
 1   open_time                1419 non-null   int64
 2   ticker                   1419 non-null   object
 3   open                     1419 non-null   float64
 4   high                     1419 non-null   float64
 5   low                      1419 non-null   float64
 6   close                    1419 non-null   float64
 7   adj_close                1419 non-null   float64
 8   volume                   1419 non-null   int64
 9   type                     1419 non-null   object
 10  ema_adj_close_200p       1220 non-null   float32
 11  ema_adj_close_200p_diff  1220 non-null   float32
 12  ema_close_200p           1220 non-null   float32
 13  ema_close_200p_diff      1220 non-null   float32
 14  rsi                      1405 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 144.2+ KB
Ticker: CRFF11.SA - Shape (1043, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1043 entries, 0 to 1042
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1043 non-null   object
 1   open_time                1043 non-null   int64
 2   ticker                   1043 non-null   object
 3   open                     1043 non-null   float64
 4   high                     1043 non-null   float64
 5   low                      1043 non-null   float64
 6   close                    1043 non-null   float64
 7   adj_close                1043 non-null   float64
 8   volume                   1043 non-null   int64
 9   type                     1043 non-null   object
 10  ema_adj_close_200p       844 non-null    float32
 11  ema_adj_close_200p_diff  844 non-null    float32
 12  ema_close_200p           844 non-null    float32
 13  ema_close_200p_diff      844 non-null    float32
 14  rsi                      1029 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 106.1+ KB
Ticker: BPML11.SA - Shape (941, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              941 non-null    object
 1   open_time                941 non-null    int64
 2   ticker                   941 non-null    object
 3   open                     941 non-null    float64
 4   high                     941 non-null    float64
 5   low                      941 non-null    float64
 6   close                    941 non-null    float64
 7   adj_close                941 non-null    float64
 8   volume                   941 non-null    int64
 9   type                     941 non-null    object
 10  ema_adj_close_200p       742 non-null    float32
 11  ema_adj_close_200p_diff  742 non-null    float32
 12  ema_close_200p           742 non-null    float32
 13  ema_close_200p_diff      742 non-null    float32
 14  rsi                      927 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.7+ KB
Ticker: BBAS3.SA - Shape (5916, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5916 entries, 0 to 5915
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5916 non-null   object
 1   open_time                5916 non-null   int64
 2   ticker                   5916 non-null   object
 3   open                     5916 non-null   float64
 4   high                     5916 non-null   float64
 5   low                      5916 non-null   float64
 6   close                    5916 non-null   float64
 7   adj_close                5916 non-null   float64
 8   volume                   5916 non-null   int64
 9   type                     5916 non-null   object
 10  ema_adj_close_200p       5717 non-null   float32
 11  ema_adj_close_200p_diff  5717 non-null   float32
 12  ema_close_200p           5717 non-null   float32
 13  ema_close_200p_diff      5717 non-null   float32
 14  rsi                      5902 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 601.0+ KB
Ticker: CEBR5.SA - Shape (3954, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3954 entries, 0 to 3953
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3954 non-null   object
 1   open_time                3954 non-null   int64
 2   ticker                   3954 non-null   object
 3   open                     3954 non-null   float64
 4   high                     3954 non-null   float64
 5   low                      3954 non-null   float64
 6   close                    3954 non-null   float64
 7   adj_close                3954 non-null   float64
 8   volume                   3954 non-null   int64
 9   type                     3954 non-null   object
 10  ema_adj_close_200p       3755 non-null   float32
 11  ema_adj_close_200p_diff  3755 non-null   float32
 12  ema_close_200p           3755 non-null   float32
 13  ema_close_200p_diff      3755 non-null   float32
 14  rsi                      3937 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.7+ KB
Ticker: HBTS5.SA - Shape (3949, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3949 entries, 0 to 3948
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3949 non-null   object
 1   open_time                3949 non-null   int64
 2   ticker                   3949 non-null   object
 3   open                     3949 non-null   float64
 4   high                     3949 non-null   float64
 5   low                      3949 non-null   float64
 6   close                    3949 non-null   float64
 7   adj_close                3949 non-null   float64
 8   volume                   3949 non-null   int64
 9   type                     3949 non-null   object
 10  ema_adj_close_200p       3750 non-null   float32
 11  ema_adj_close_200p_diff  3750 non-null   float32
 12  ema_close_200p           3750 non-null   float32
 13  ema_close_200p_diff      3750 non-null   float32
 14  rsi                      3935 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.2+ KB
Ticker: TPIS3.SA - Shape (4059, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4059 entries, 0 to 4058
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4059 non-null   object
 1   open_time                4059 non-null   int64
 2   ticker                   4059 non-null   object
 3   open                     4059 non-null   float64
 4   high                     4059 non-null   float64
 5   low                      4059 non-null   float64
 6   close                    4059 non-null   float64
 7   adj_close                4059 non-null   float64
 8   volume                   4059 non-null   int64
 9   type                     4059 non-null   object
 10  ema_adj_close_200p       3860 non-null   float32
 11  ema_adj_close_200p_diff  3860 non-null   float32
 12  ema_close_200p           3860 non-null   float32
 13  ema_close_200p_diff      3860 non-null   float32
 14  rsi                      4045 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 412.4+ KB
Ticker: ITSA3.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: RBIR11.SA - Shape (933, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 933 entries, 0 to 932
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              933 non-null    object
 1   open_time                933 non-null    int64
 2   ticker                   933 non-null    object
 3   open                     933 non-null    float64
 4   high                     933 non-null    float64
 5   low                      933 non-null    float64
 6   close                    933 non-null    float64
 7   adj_close                933 non-null    float64
 8   volume                   933 non-null    int64
 9   type                     933 non-null    object
 10  ema_adj_close_200p       734 non-null    float32
 11  ema_adj_close_200p_diff  734 non-null    float32
 12  ema_close_200p           734 non-null    float32
 13  ema_close_200p_diff      734 non-null    float32
 14  rsi                      919 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 94.9+ KB
Ticker: VIVA3.SA - Shape (1027, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1027 entries, 0 to 1026
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1027 non-null   object
 1   open_time                1027 non-null   int64
 2   ticker                   1027 non-null   object
 3   open                     1027 non-null   float64
 4   high                     1027 non-null   float64
 5   low                      1027 non-null   float64
 6   close                    1027 non-null   float64
 7   adj_close                1027 non-null   float64
 8   volume                   1027 non-null   int64
 9   type                     1027 non-null   object
 10  ema_adj_close_200p       828 non-null    float32
 11  ema_adj_close_200p_diff  828 non-null    float32
 12  ema_close_200p           828 non-null    float32
 13  ema_close_200p_diff      828 non-null    float32
 14  rsi                      1013 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 104.4+ KB
Ticker: BRCR11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: HAGA3.SA - Shape (5426, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5426 entries, 0 to 5425
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5426 non-null   object
 1   open_time                5426 non-null   int64
 2   ticker                   5426 non-null   object
 3   open                     5426 non-null   float64
 4   high                     5426 non-null   float64
 5   low                      5426 non-null   float64
 6   close                    5426 non-null   float64
 7   adj_close                5426 non-null   float64
 8   volume                   5426 non-null   int64
 9   type                     5426 non-null   object
 10  ema_adj_close_200p       5227 non-null   float32
 11  ema_adj_close_200p_diff  5227 non-null   float32
 12  ema_close_200p           5227 non-null   float32
 13  ema_close_200p_diff      5227 non-null   float32
 14  rsi                      4180 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 551.2+ KB
Ticker: CIEL3.SA - Shape (3582, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3582 entries, 0 to 3581
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3582 non-null   object
 1   open_time                3582 non-null   int64
 2   ticker                   3582 non-null   object
 3   open                     3582 non-null   float64
 4   high                     3582 non-null   float64
 5   low                      3582 non-null   float64
 6   close                    3582 non-null   float64
 7   adj_close                3582 non-null   float64
 8   volume                   3582 non-null   int64
 9   type                     3582 non-null   object
 10  ema_adj_close_200p       3383 non-null   float32
 11  ema_adj_close_200p_diff  3383 non-null   float32
 12  ema_close_200p           3383 non-null   float32
 13  ema_close_200p_diff      3383 non-null   float32
 14  rsi                      3568 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 363.9+ KB
Ticker: SNFF11.SA - Shape (642, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642 entries, 0 to 641
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              642 non-null    object
 1   open_time                642 non-null    int64
 2   ticker                   642 non-null    object
 3   open                     642 non-null    float64
 4   high                     642 non-null    float64
 5   low                      642 non-null    float64
 6   close                    642 non-null    float64
 7   adj_close                642 non-null    float64
 8   volume                   642 non-null    int64
 9   type                     642 non-null    object
 10  ema_adj_close_200p       443 non-null    float32

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: RDNI3.SA - Shape (4176, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4176 entries, 0 to 4175
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4176 non-null   object
 1   open_time                4176 non-null   int64
 2   ticker                   4176 non-null   object
 3   open                     4176 non-null   float64
 4   high                     4176 non-null   float64
 5   low                      4176 non-null   float64
 6   close                    4176 non-null   float64
 7   adj_close                4176 non-null   float64
 8   volume                   4176 non-null   int64
 9   type                     4176 non-null   object
 10  ema_adj_close_200p       3977 non-null   float32
 11  ema_adj_close_200p_diff  3977 non-null   float32
 12  ema_close_200p           3977 non-null   float32
 13  ema_close_200p_diff      3977 non-null   float32
 14  rsi                      4162 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 424.3+ KB
Ticker: DXCO3.SA - Shape (4016, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4016 entries, 0 to 4015
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4016 non-null   object
 1   open_time                4016 non-null   int64
 2   ticker                   4016 non-null   object
 3   open                     4016 non-null   float64
 4   high                     4016 non-null   float64
 5   low                      4016 non-null   float64
 6   close                    4016 non-null   float64
 7   adj_close                4016 non-null   float64
 8   volume                   4016 non-null   int64
 9   type                     4016 non-null   object
 10  ema_adj_close_200p       3817 non-null   float32
 11  ema_adj_close_200p_diff  3817 non-null   float32
 12  ema_close_200p           3817 non-null   float32
 13  ema_close_200p_diff      3817 non-null   float32
 14  rsi                      4002 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 408.0+ KB
Ticker: IGTI3.SA - Shape (5885, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5885 entries, 0 to 5884
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5885 non-null   object
 1   open_time                5885 non-null   int64
 2   ticker                   5885 non-null   object
 3   open                     5885 non-null   float64
 4   high                     5885 non-null   float64
 5   low                      5885 non-null   float64
 6   close                    5885 non-null   float64
 7   adj_close                5885 non-null   float64
 8   volume                   5885 non-null   int64
 9   type                     5885 non-null   object
 10  ema_adj_close_200p       5686 non-null   float32
 11  ema_adj_close_200p_diff  5686 non-null   float32
 12  ema_close_200p           5686 non-null   float32
 13  ema_close_200p_diff      5686 non-null   float32
 14  rsi                      5871 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 597.8+ KB
Ticker: CRPG5.SA - Shape (6006, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6006 entries, 0 to 6005
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6006 non-null   object
 1   open_time                6006 non-null   int64
 2   ticker                   6006 non-null   object
 3   open                     6006 non-null   float64
 4   high                     6006 non-null   float64
 5   low                      6006 non-null   float64
 6   close                    6006 non-null   float64
 7   adj_close                6006 non-null   float64
 8   volume                   6006 non-null   int64
 9   type                     6006 non-null   object
 10  ema_adj_close_200p       5807 non-null   float32
 11  ema_adj_close_200p_diff  5807 non-null   float32
 12  ema_close_200p           5807 non-null   float32
 13  ema_close_200p_diff      5807 non-null   float32
 14  rsi                      5992 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.1+ KB
Ticker: RCRB11.SA - Shape (941, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              941 non-null    object
 1   open_time                941 non-null    int64
 2   ticker                   941 non-null    object
 3   open                     941 non-null    float64
 4   high                     941 non-null    float64
 5   low                      941 non-null    float64
 6   close                    941 non-null    float64
 7   adj_close                941 non-null    float64
 8   volume                   941 non-null    int64
 9   type                     941 non-null    object
 10  ema_adj_close_200p       742 non-null    float32
 11  ema_adj_close_200p_diff  742 non-null    float32
 12  ema_close_200p           742 non-null    float32
 13  ema_close_200p_diff      742 non-null    float32
 14  rsi                      927 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.7+ KB
Ticker: EXES11.SA - Shape (357, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              357 non-null    object
 1   open_time                357 non-null    int64
 2   ticker                   357 non-null    object
 3   open                     357 non-null    float64
 4   high                     357 non-null    float64
 5   low                      357 non-null    float64
 6   close                    357 non-null    float64
 7   adj_close                357 non-null    float64
 8   volume                   357 non-null    int64
 9   type                     357 non-null    object
 10  ema_adj_close_200p       158 non-null    float32
 11  ema_adj_close_200p_diff  158 non-null    float32
 12  ema_close_200p           158 non-null    float32
 13  ema_close_200p_diff      158 non-null    float32
 14  rsi                      343 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 36.4+ KB
Ticker: CGAS3.SA - Shape (5682, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5682 entries, 0 to 5681
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5682 non-null   object
 1   open_time                5682 non-null   int64
 2   ticker                   5682 non-null   object
 3   open                     5682 non-null   float64
 4   high                     5682 non-null   float64
 5   low                      5682 non-null   float64
 6   close                    5682 non-null   float64
 7   adj_close                5682 non-null   float64
 8   volume                   5682 non-null   int64
 9   type                     5682 non-null   object
 10  ema_adj_close_200p       5483 non-null   float32
 11  ema_adj_close_200p_diff  5483 non-null   float32
 12  ema_close_200p           5483 non-null   float32
 13  ema_close_200p_diff      5483 non-null   float32
 14  rsi                      5668 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 577.2+ KB
Ticker: MSPA4.SA - Shape (4359, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4359 entries, 0 to 4358
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4359 non-null   object
 1   open_time                4359 non-null   int64
 2   ticker                   4359 non-null   object
 3   open                     4359 non-null   float64
 4   high                     4359 non-null   float64
 5   low                      4359 non-null   float64
 6   close                    4359 non-null   float64
 7   adj_close                4359 non-null   float64
 8   volume                   4359 non-null   int64
 9   type                     4359 non-null   object
 10  ema_adj_close_200p       4160 non-null   float32
 11  ema_adj_close_200p_diff  4160 non-null   float32
 12  ema_close_200p           4160 non-null   float32
 13  ema_close_200p_diff      4160 non-null   float32
 14  rsi                      4345 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 442.8+ KB
Ticker: ECPR3.SA - Shape (6005, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6005 entries, 0 to 6004
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6005 non-null   object
 1   open_time                6005 non-null   int64
 2   ticker                   6005 non-null   object
 3   open                     6005 non-null   float64
 4   high                     6005 non-null   float64
 5   low                      6005 non-null   float64
 6   close                    6005 non-null   float64
 7   adj_close                6005 non-null   float64
 8   volume                   6005 non-null   int64
 9   type                     6005 non-null   object
 10  ema_adj_close_200p       5806 non-null   float32
 11  ema_adj_close_200p_diff  5806 non-null   float32
 12  ema_close_200p           5806 non-null   float32
 13  ema_close_200p_diff      5806 non-null   float32
 14  rsi                      5991 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.0+ KB
Ticker: VISC11.SA - Shape (1511, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1511 non-null   object
 1   open_time                1511 non-null   int64
 2   ticker                   1511 non-null   object
 3   open                     1511 non-null   float64
 4   high                     1511 non-null   float64
 5   low                      1511 non-null   float64
 6   close                    1511 non-null   float64
 7   adj_close                1511 non-null   float64
 8   volume                   1511 non-null   int64
 9   type                     1511 non-null   object
 10  ema_adj_close_200p       1312 non-null   float32
 11  ema_adj_close_200p_diff  1312 non-null   float32
 12  ema_close_200p           1312 non-null   float32
 13  ema_close_200p_diff      1312 non-null   float32
 14  rsi                      1497 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 153.6+ KB
Ticker: VCRR11.SA - Shape (447, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 447 entries, 0 to 446
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              447 non-null    object
 1   open_time                447 non-null    int64
 2   ticker                   447 non-null    object
 3   open                     447 non-null    float64
 4   high                     447 non-null    float64
 5   low                      447 non-null    float64
 6   close                    447 non-null    float64
 7   adj_close                447 non-null    float64
 8   volume                   447 non-null    int64
 9   type                     447 non-null    object
 10  ema_adj_close_200p       248 non-null    float32
 11  ema_adj_close_200p_diff  248 non-null    float32
 12  ema_close_200p           248 non-null    float32
 13  ema_close_200p_diff      248 non-null    float32
 14  rsi                      433 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 45.5+ KB
Ticker: CMIG4.SA - Shape (6007, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6007 entries, 0 to 6006
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6007 non-null   object
 1   open_time                6007 non-null   int64
 2   ticker                   6007 non-null   object
 3   open                     6007 non-null   float64
 4   high                     6007 non-null   float64
 5   low                      6007 non-null   float64
 6   close                    6007 non-null   float64
 7   adj_close                6007 non-null   float64
 8   volume                   6007 non-null   int64
 9   type                     6007 non-null   object
 10  ema_adj_close_200p       5808 non-null   float32
 11  ema_adj_close_200p_diff  5808 non-null   float32
 12  ema_close_200p           5808 non-null   float32
 13  ema_close_200p_diff      5808 non-null   float32
 14  rsi                      5993 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.2+ KB
Ticker: RECV3.SA - Shape (644, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 644 entries, 0 to 643
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              644 non-null    object
 1   open_time                644 non-null    int64
 2   ticker                   644 non-null    object
 3   open                     644 non-null    float64
 4   high                     644 non-null    float64
 5   low                      644 non-null    float64
 6   close                    644 non-null    float64
 7   adj_close                644 non-null    float64
 8   volume                   644 non-null    int64
 9   type                     644 non-null    object
 10  ema_adj_close_200p       445 non-null    float32
 11  ema_adj_close_200p_diff  445 non-null    float32
 12  ema_close_200p           445 non-null    float32
 13  ema_close_200p_diff      445 non-null    float32
 14  rsi                      630 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 65.5+ KB
Ticker: VIUR11.SA - Shape (622, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 622 entries, 0 to 621
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              622 non-null    object
 1   open_time                622 non-null    int64
 2   ticker                   622 non-null    object
 3   open                     622 non-null    float64
 4   high                     622 non-null    float64
 5   low                      622 non-null    float64
 6   close                    622 non-null    float64
 7   adj_close                622 non-null    float64
 8   volume                   622 non-null    int64
 9   type                     622 non-null    object
 10  ema_adj_close_200p       423 non-null    float32
 11  ema_adj_close_200p_diff  423 non-null    float32
 12  ema_close_200p           423 non-null    float32
 13  ema_close_200p_diff      423 non-null    float32
 14  rsi                      608 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 63.3+ KB
Ticker: LUXM4.SA - Shape (3952, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3952 entries, 0 to 3951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3952 non-null   object
 1   open_time                3952 non-null   int64
 2   ticker                   3952 non-null   object
 3   open                     3952 non-null   float64
 4   high                     3952 non-null   float64
 5   low                      3952 non-null   float64
 6   close                    3952 non-null   float64
 7   adj_close                3952 non-null   float64
 8   volume                   3952 non-null   int64
 9   type                     3952 non-null   object
 10  ema_adj_close_200p       3753 non-null   float32
 11  ema_adj_close_200p_diff  3753 non-null   float32
 12  ema_close_200p           3753 non-null   float32
 13  ema_close_200p_diff      3753 non-null   float32
 14  rsi                      3938 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.5+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: GCOI11.SA - Shape (150, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              150 non-null    object
 1   open_time                150 non-null    int64
 2   ticker                   150 non-null    object
 3   open                     150 non-null    float64
 4   high                     150 non-null    float64
 5   low                      150 non-null    float64
 6   close                    150 non-null    float64
 7   adj_close                150 non-null    float64
 8   volume                   150 non-null    int64
 9   type                     150 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      99 non-null     float64
dtypes: float64(6), int64(2), object(7)
memory usage: 17.7+ KB
Ticker: CARE11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: ATMP3.SA - Shape (4539, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4539 entries, 0 to 4538
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4539 non-null   object
 1   open_time                4539 non-null   int64
 2   ticker                   4539 non-null   object
 3   open                     4539 non-null   float64
 4   high                     4539 non-null   float64
 5   low                      4539 non-null   float64
 6   close                    4539 non-null   float64
 7   adj_close                4539 non-null   float64
 8   volume                   4539 non-null   int64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: TOTS3.SA - Shape (4406, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4406 entries, 0 to 4405
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4406 non-null   object
 1   open_time                4406 non-null   int64
 2   ticker                   4406 non-null   object
 3   open                     4406 non-null   float64
 4   high                     4406 non-null   float64
 5   low                      4406 non-null   float64
 6   close                    4406 non-null   float64
 7   adj_close                4406 non-null   float64
 8   volume                   4406 non-null   int64
 9   type                     4406 non-null   object
 10  ema_adj_close_200p       4207 non-null   float32
 11  ema_adj_close_200p_diff  4207 non-null   float32
 12  ema_close_200p           4207 non-null   float32
 13  ema_close_200p_diff      4207 non-null   float32
 14  rsi                      4392 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 447.6+ KB
Ticker: PINE4.SA - Shape (4135, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4135 entries, 0 to 4134
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4135 non-null   object
 1   open_time                4135 non-null   int64
 2   ticker                   4135 non-null   object
 3   open                     4135 non-null   float64
 4   high                     4135 non-null   float64
 5   low                      4135 non-null   float64
 6   close                    4135 non-null   float64
 7   adj_close                4135 non-null   float64
 8   volume                   4135 non-null   int64
 9   type                     4135 non-null   object
 10  ema_adj_close_200p       3936 non-null   float32
 11  ema_adj_close_200p_diff  3936 non-null   float32
 12  ema_close_200p           3936 non-null   float32
 13  ema_close_200p_diff      3936 non-null   float32
 14  rsi                      4121 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 420.1+ KB
Ticker: ALZM11.SA - Shape (653, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              653 non-null    object
 1   open_time                653 non-null    int64
 2   ticker                   653 non-null    object
 3   open                     653 non-null    float64
 4   high                     653 non-null    float64
 5   low                      653 non-null    float64
 6   close                    653 non-null    float64
 7   adj_close                653 non-null    float64
 8   volume                   653 non-null    int64
 9   type                     653 non-null    object
 10  ema_adj_close_200p       454 non-null    float32
 11  ema_adj_close_200p_diff  454 non-null    float32
 12  ema_close_200p           454 non-null    float32
 13  ema_close_200p_diff      454 non-null    float32
 14  rsi                      639 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 66.4+ KB
Ticker: MDIA3.SA - Shape (4247, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4247 entries, 0 to 4246
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4247 non-null   object
 1   open_time                4247 non-null   int64
 2   ticker                   4247 non-null   object
 3   open                     4247 non-null   float64
 4   high                     4247 non-null   float64
 5   low                      4247 non-null   float64
 6   close                    4247 non-null   float64
 7   adj_close                4247 non-null   float64
 8   volume                   4247 non-null   int64
 9   type                     4247 non-null   object
 10  ema_adj_close_200p       4048 non-null   float32
 11  ema_adj_close_200p_diff  4048 non-null   float32
 12  ema_close_200p           4048 non-null   float32
 13  ema_close_200p_diff      4048 non-null   float32
 14  rsi                      4233 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 431.5+ KB
Ticker: CGRA4.SA - Shape (5122, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5122 entries, 0 to 5121
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5122 non-null   object
 1   open_time                5122 non-null   int64
 2   ticker                   5122 non-null   object
 3   open                     5122 non-null   float64
 4   high                     5122 non-null   float64
 5   low                      5122 non-null   float64
 6   close                    5122 non-null   float64
 7   adj_close                5122 non-null   float64
 8   volume                   5122 non-null   int64
 9   type                     5122 non-null   object
 10  ema_adj_close_200p       4923 non-null   float32
 11  ema_adj_close_200p_diff  4923 non-null   float32
 12  ema_close_200p           4923 non-null   float32
 13  ema_close_200p_diff      4923 non-null   float32
 14  rsi                      5108 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 520.3+ KB
Ticker: RNDP11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: AURE3.SA - Shape (421, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              421 non-null    object
 1   open_time                421 non-null    int64
 2   ticker                   421 non-null    object
 3   open                     421 non-null    float64
 4   high                     421 non-null    float64
 5   low                      421 non-null    float64
 6   close                    421 non-null    float64
 7   adj_close                421 non-null    float64
 8   volume                   421 non-null    int64
 9   type                     421 non-null    object
 10  ema_adj_close_200p       222 non-null    float32
 11  ema_adj_close_200p_diff  222 non-null    float32
 12  ema_close_200p           222 non-null    float32
 13  ema_close_200p_diff      222 non-null    float32
 14  rsi                      407 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 42.9+ KB
Ticker: LOFT11B.SA - Shape (939, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              939 non-null    object
 1   open_time                939 non-null    int64
 2   ticker                   939 non-null    object
 3   open                     939 non-null    float64
 4   high                     939 non-null    float64
 5   low                      939 non-null    float64
 6   close                    939 non-null    float64
 7   adj_close                939 non-null    float64
 8   volume                   939 non-null    int64
 9   type                     939 non-null    object
 10  ema_adj_close_200p       740 non-null    float32
 11  ema_adj_close_200p_diff  740 non-null    float32
 12  ema_close_200p           740 non-null    float32
 13  ema_close_200p_diff      740 non-null    float32
 14  rsi                      925 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.5+ KB
Ticker: HSML11.SA - Shape (1067, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1067 non-null   object
 1   open_time                1067 non-null   int64
 2   ticker                   1067 non-null   object
 3   open                     1067 non-null   float64
 4   high                     1067 non-null   float64
 5   low                      1067 non-null   float64
 6   close                    1067 non-null   float64
 7   adj_close                1067 non-null   float64
 8   volume                   1067 non-null   int64
 9   type                     1067 non-null   object
 10  ema_adj_close_200p       868 non-null    float32
 11  ema_adj_close_200p_diff  868 non-null    float32
 12  ema_close_200p           868 non-null    float32
 13  ema_close_200p_diff      868 non-null    float32
 14  rsi                      1053 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 108.5+ KB
Ticker: CAMB3.SA - Shape (3306, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3306 entries, 0 to 3305
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3306 non-null   object
 1   open_time                3306 non-null   int64
 2   ticker                   3306 non-null   object
 3   open                     3306 non-null   float64
 4   high                     3306 non-null   float64
 5   low                      3306 non-null   float64
 6   close                    3306 non-null   float64
 7   adj_close                3306 non-null   float64
 8   volume                   3306 non-null   int64
 9   type                     3306 non-null   object
 10  ema_adj_close_200p       3107 non-null   float32
 11  ema_adj_close_200p_diff  3107 non-null   float32
 12  ema_close_200p           3107 non-null   float32
 13  ema_close_200p_diff      3107 non-null   float32
 14  rsi                      2961 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 335.9+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: KNUQ11.SA - Shape (24, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              24 non-null     object
 1   open_time                24 non-null     int64
 2   ticker                   24 non-null     object
 3   open                     24 non-null     float64
 4   high                     24 non-null     float64
 5   low                      24 non-null     float64
 6   close                    24 non-null     float64
 7   adj_close                24 non-null     float64
 8   volume                   24 non-null     int64
 9   type                     24 non-null     object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      10 non-null     float64
dtypes: float64(6), int64(2), object(7)
memory usage: 2.9+ KB
Ticker: RBLG11.SA - Shape (350, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              350 non-null    object
 1   open_time                350 non-null    int64
 2   ticker                   350 non-null    object
 3   open                     350 non-null    float64
 4   high                     350 non-null    float64
 5   low                      350 non-null    float64
 6   close                    350 non-null    float64
 7   adj_close                350 non-null    float64
 8   volume                   350 non-null    int64
 9   type                     350 non-null    object
 10  ema_adj_close_200p       151 non-null    float32
 11  ema_adj_close_200p_diff  151 non-null    float32
 12  ema_close_200p           151 non-null    float32
 13  ema_close_200p_diff      151 non-null    float32
 14  rsi                      336 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 35.7+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: TMPS11.SA - Shape (143, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              143 non-null    object
 1   open_time                143 non-null    int64
 2   ticker                   143 non-null    object
 3   open                     143 non-null    float64
 4   high                     143 non-null    float64
 5   low                      143 non-null    float64
 6   close                    143 non-null    float64
 7   adj_close                143 non-null    float64
 8   volume                   143 non-null    int64
 9   type                     143 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      129 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 16.9+ KB
Ticker: MTIG3.SA - Shape (5299, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5299 entries, 0 to 5298
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5299 non-null   object
 1   open_time                5299 non-null   int64
 2   ticker                   5299 non-null   object
 3   open                     5299 non-null   float64
 4   high                     5299 non-null   float64
 5   low                      5299 non-null   float64
 6   close                    5299 non-null   float64
 7   adj_close                5299 non-null   float64
 8   volume                   5299 non-null   int64
 9   type                     5299 non-null   object
 10  ema_adj_close_200p       5100 non-null   float32
 11  ema_adj_close_200p_diff  5100 non-null   float32
 12  ema_close_200p           5100 non-null   float32
 13  ema_close_200p_diff      5100 non-null   float32
 14  rsi                      5285 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 538.3+ KB
Ticker: CEOC11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: BTAL11.SA - Shape (704, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 704 entries, 0 to 703
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              704 non-null    object
 1   open_time                704 non-null    int64
 2   ticker                   704 non-null    object
 3   open                     704 non-null    float64
 4   high                     704 non-null    float64
 5   low                      704 non-null    float64
 6   close                    704 non-null    float64
 7   adj_close                704 non-null    float64
 8   volume                   704 non-null    int64
 9   type                     704 non-null    object
 10  ema_adj_close_200p       505 non-null    float32
 11  ema_adj_close_200p_diff  505 non-null    float32
 12  ema_close_200p           505 non-null    float32
 13  ema_close_200p_diff      505 non-null    float32
 14  rsi                      690 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 71.6+ KB
Ticker: PLCA11.SA - Shape (327, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327 entries, 0 to 326
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              327 non-null    object
 1   open_time                327 non-null    int64
 2   ticker                   327 non-null    object
 3   open                     327 non-null    float64
 4   high                     327 non-null    float64
 5   low                      327 non-null    float64
 6   close                    327 non-null    float64
 7   adj_close                327 non-null    float64
 8   volume                   327 non-null    int64
 9   type                     327 non-null    object
 10  ema_adj_close_200p       128 non-null    float32
 11  ema_adj_close_200p_diff  128 non-null    float32
 12  ema_close_200p           128 non-null    float32
 13  ema_close_200p_diff      128 non-null    float32
 14  rsi                      313 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 33.3+ KB
Ticker: AZUL4.SA - Shape (1654, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1654 entries, 0 to 1653
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1654 non-null   object
 1   open_time                1654 non-null   int64
 2   ticker                   1654 non-null   object
 3   open                     1654 non-null   float64
 4   high                     1654 non-null   float64
 5   low                      1654 non-null   float64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Ticker: B3SA3.SA - Shape (3990, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3990 entries, 0 to 3989
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3990 non-null   object
 1   open_time                3990 non-null   int64
 2   ticker                   3990 non-null   object
 3   open                     3990 non-null   float64
 4   high                     3990 non-null   float64
 5   low                      3990 non-null   float64
 6   close                    3990 non-null   float64
 7   adj_close                3990 non-null   float64
 8   volume                   3990 non-null   int64
 9   type                     3990 non-null   object
 10  ema_adj_close_200p       3791 non-null   float32
 11  ema_adj_close_200p_diff  3791 non-null   float32
 12  ema_close_200p           3791 non-null   float32
 13  ema_close_200p_diff      3791 non-null   float32
 14  rsi                      3976 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 405.4+ KB
Ticker: ENMT4.SA - Shape (6005, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6005 entries, 0 to 6004
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              6005 non-null   object
 1   open_time                6005 non-null   int64
 2   ticker                   6005 non-null   object
 3   open                     6005 non-null   float64
 4   high                     6005 non-null   float64
 5   low                      6005 non-null   float64
 6   close                    6005 non-null   float64
 7   adj_close                6005 non-null   float64
 8   volume                   6005 non-null   int64
 9   type                     6005 non-null   object
 10  ema_adj_close_200p       5806 non-null   float32
 11  ema_adj_close_200p_diff  5806 non-null   float32
 12  ema_close_200p           5806 non-null   float32
 13  ema_close_200p_diff      5806 non-null   float32
 14  rsi                      5991 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 610.0+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: PNRC11.SA - Shape (100, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              100 non-null    object
 1   open_time                100 non-null    int64
 2   ticker                   100 non-null    object
 3   open                     100 non-null    float64
 4   high                     100 non-null    float64
 5   low                      100 non-null    float64
 6   close                    100 non-null    float64
 7   adj_close                100 non-null    float64
 8   volume                   100 non-null    int64
 9   type                     100 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      83 non-null     float64
dtypes: float64(6), int64(2), object(7)
memory usage: 11.8+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: BICE11.SA - Shape (58, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              58 non-null     object
 1   open_time                58 non-null     int64
 2   ticker                   58 non-null     object
 3   open                     58 non-null     float64
 4   high                     58 non-null     float64
 5   low                      58 non-null     float64
 6   close                    58 non-null     float64
 7   adj_close                58 non-null     float64
 8   volume                   58 non-null     int64
 9   type                     58 non-null     object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      44 non-null     float64
dtypes: float64(6), int64(2), object(7)
memory usage: 6.9+ KB
Ticker: OFSA3.SA - Shape (2265, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2265 entries, 0 to 2264
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2265 non-null   object
 1   open_time                2265 non-null   int64
 2   ticker                   2265 non-null   object
 3   open                     2265 non-null   float64
 4   high                     2265 non-null   float64
 5   low                      2265 non-null   float64
 6   close                    2265 non-null   float64
 7   adj_close                2265 non-null   float64
 8   volume                   2265 non-null   int64
 9   type                     2265 non-null   object
 10  ema_adj_close_200p       2066 non-null   float32
 11  ema_adj_close_200p_diff  2066 non-null   float32
 12  ema_close_200p           2066 non-null   float32
 13  ema_close_200p_diff      2066 non-null   float32
 14  rsi                      2251 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 230.2+ KB
Ticker: CVCB3.SA - Shape (2479, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2479 entries, 0 to 2478
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2479 non-null   object
 1   open_time                2479 non-null   int64
 2   ticker                   2479 non-null   object
 3   open                     2479 non-null   float64
 4   high                     2479 non-null   float64
 5   low                      2479 non-null   float64
 6   close                    2479 non-null   float64
 7   adj_close                2479 non-null   float64
 8   volume                   2479 non-null   int64
 9   type                     2479 non-null   object
 10  ema_adj_close_200p       2280 non-null   float32
 11  ema_adj_close_200p_diff  2280 non-null   float32
 12  ema_close_200p           2280 non-null   float32
 13  ema_close_200p_diff      2280 non-null   float32
 14  rsi                      2465 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 251.9+ KB
Ticker: HUCG11.SA - Shape (388, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              388 non-null    object
 1   open_time                388 non-null    int64
 2   ticker                   388 non-null    object
 3   open                     388 non-null    float64
 4   high                     388 non-null    float64
 5   low                      388 non-null    float64
 6   close                    388 non-null    float64
 7   adj_close                388 non-null    float64
 8   volume                   388 non-null    int64
 9   type                     388 non-null    object
 10  ema_adj_close_200p       189 non-null    float32
 11  ema_adj_close_200p_diff  189 non-null    float32
 12  ema_close_200p           189 non-null    float32
 13  ema_close_200p_diff      189 non-null    float32
 14  rsi                      374 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 39.5+ KB
Ticker: MRSA5B.SA - Shape (1813, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1813 entries, 0 to 1812
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1813 non-null   object
 1   open_time                1813 non-null   int64
 2   ticker                   1813 non-null   object
 3   open                     1813 non-null   float64
 4   high                     1813 non-null   float64
 5   low                      1813 non-null   float64
 6   close                    1813 non-null   float64
 7   adj_close                1813 non-null   float64
 8   volume                   1813 non-null   int64
 9   type                     1813 non-null   object
 10  ema_adj_close_200p       1614 non-null   float32
 11  ema_adj_close_200p_diff  1614 non-null   float32
 12  ema_close_200p           1614 non-null   float32
 13  ema_close_200p_diff      1614 non-null   float32
 14  rsi                      1799 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 184.3+ KB
Ticker: CASN3.SA - Shape (4335, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4335 entries, 0 to 4334
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4335 non-null   object
 1   open_time                4335 non-null   int64
 2   ticker                   4335 non-null   object
 3   open                     4335 non-null   float64
 4   high                     4335 non-null   float64
 5   low                      4335 non-null   float64
 6   close                    4335 non-null   float64
 7   adj_close                4335 non-null   float64
 8   volume                   4335 non-null   int64
 9   type                     4335 non-null   object
 10  ema_adj_close_200p       4136 non-null   float32
 11  ema_adj_close_200p_diff  4136 non-null   float32
 12  ema_close_200p           4136 non-null   float32
 13  ema_close_200p_diff      4136 non-null   float32
 14  rsi                      4193 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 440.4+ KB
Ticker: BAHI3.SA - Shape (5385, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5385 entries, 0 to 5384
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5385 non-null   object
 1   open_time                5385 non-null   int64
 2   ticker                   5385 non-null   object
 3   open                     5385 non-null   float64
 4   high                     5385 non-null   float64
 5   low                      5385 non-null   float64
 6   close                    5385 non-null   float64
 7   adj_close                5385 non-null   float64
 8   volume                   5385 non-null   int64
 9   type                     5385 non-null   object
 10  ema_adj_close_200p       5186 non-null   float32
 11  ema_adj_close_200p_diff  5186 non-null   float32
 12  ema_close_200p           5186 non-null   float32
 13  ema_close_200p_diff      5186 non-null   float32
 14  rsi                      5202 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 547.0+ KB
Ticker: TAEE4.SA - Shape (1636, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1636 entries, 0 to 1635
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1636 non-null   object
 1   open_time                1636 non-null   int64
 2   ticker                   1636 non-null   object
 3   open                     1636 non-null   float64
 4   high                     1636 non-null   float64
 5   low                      1636 non-null   float64
 6   close                    1636 non-null   float64
 7   adj_close                1636 non-null   float64
 8   volume                   1636 non-null   int64
 9   type                     1636 non-null   object
 10  ema_adj_close_200p       1437 non-null   float32
 11  ema_adj_close_200p_diff  1437 non-null   float32
 12  ema_close_200p           1437 non-null   float32
 13  ema_close_200p_diff      1437 non-null   float32
 14  rsi                      1622 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 166.3+ KB
Ticker: GURB11.SA - Shape (273, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              273 non-null    object
 1   open_time                273 non-null    int64
 2   ticker                   273 non-null    object
 3   open                     273 non-null    float64
 4   high                     273 non-null    float64
 5   low                      273 non-null    float64
 6   close                    273 non-null    float64
 7   adj_close                273 non-null    float64
 8   volume                   273 non-null    int64
 9   type                     273 non-null    object
 10  ema_adj_close_200p       74 non-null     float32
 11  ema_adj_close_200p_diff  74 non-null     float32
 12  ema_close_200p           74 non-null     float32
 13  ema_close_200p_diff      74 non-null     float32
 14  rsi                      223 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 27.9+ KB
Ticker: FIEI3.SA - Shape (4119, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4119 non-null   object
 1   open_time                4119 non-null   int64
 2   ticker                   4119 non-null   object
 3   open                     4119 non-null   float64
 4   high                     4119 non-null   float64
 5   low                      4119 non-null   float64
 6   close                    4119 non-null   float64
 7   adj_close                4119 non-null   float64
 8   volume                   4119 non-null   int64
 9   type                     4119 non-null   object
 10  ema_adj_close_200p       3920 non-null   float32
 11  ema_adj_close_200p_diff  3920 non-null   float32
 12  ema_close_200p           3920 non-null   float32
 13  ema_close_200p_diff      3920 non-null   float32
 14  rsi                      4105 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 418.5+ KB
Ticker: OULG11.SA - Shape (911, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              911 non-null    object
 1   open_time                911 non-null    int64
 2   ticker                   911 non-null    object
 3   open                     911 non-null    float64
 4   high                     911 non-null    float64
 5   low                      911 non-null    float64
 6   close                    911 non-null    float64
 7   adj_close                911 non-null    float64
 8   volume                   911 non-null    int64
 9   type                     911 non-null    object
 10  ema_adj_close_200p       712 non-null    float32
 11  ema_adj_close_200p_diff  712 non-null    float32
 12  ema_close_200p           712 non-null    float32
 13  ema_close_200p_diff      712 non-null    float32
 14  rsi                      897 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 92.7+ KB
Ticker: BICR11.SA - Shape (939, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              939 non-null    object
 1   open_time                939 non-null    int64
 2   ticker                   939 non-null    object
 3   open                     939 non-null    float64
 4   high                     939 non-null    float64
 5   low                      939 non-null    float64
 6   close                    939 non-null    float64
 7   adj_close                939 non-null    float64
 8   volume                   939 non-null    int64
 9   type                     939 non-null    object
 10  ema_adj_close_200p       740 non-null    float32
 11  ema_adj_close_200p_diff  740 non-null    float32
 12  ema_close_200p           740 non-null    float32
 13  ema_close_200p_diff      740 non-null    float32
 14  rsi                      925 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.5+ KB
Ticker: LIFE11.SA - Shape (276, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              276 non-null    object
 1   open_time                276 non-null    int64
 2   ticker                   276 non-null    object
 3   open                     276 non-null    float64
 4   high                     276 non-null    float64
 5   low                      276 non-null    float64
 6   close                    276 non-null    float64
 7   adj_close                276 non-null    float64
 8   volume                   276 non-null    int64
 9   type                     276 non-null    object
 10  ema_adj_close_200p       77 non-null     float32
 11  ema_adj_close_200p_diff  77 non-null     float32
 12  ema_close_200p           77 non-null     float32
 13  ema_close_200p_diff      77 non-null     float32
 14  rsi                      262 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 28.2+ KB
Ticker: CGAS5.SA - Shape (5635, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5635 entries, 0 to 5634
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5635 non-null   object
 1   open_time                5635 non-null   int64
 2   ticker                   5635 non-null   object
 3   open                     5635 non-null   float64
 4   high                     5635 non-null   float64
 5   low                      5635 non-null   float64
 6   close                    5635 non-null   float64
 7   adj_close                5635 non-null   float64
 8   volume                   5635 non-null   int64
 9   type                     5635 non-null   object
 10  ema_adj_close_200p       5436 non-null   float32
 11  ema_adj_close_200p_diff  5436 non-null   float32
 12  ema_close_200p           5436 non-null   float32
 13  ema_close_200p_diff      5436 non-null   float32
 14  rsi                      5621 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 572.4+ KB
Ticker: CTSA3.SA - Shape (5797, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5797 entries, 0 to 5796
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5797 non-null   object
 1   open_time                5797 non-null   int64
 2   ticker                   5797 non-null   object
 3   open                     5797 non-null   float64
 4   high                     5797 non-null   float64
 5   low                      5797 non-null   float64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4072 entries, 0 to 4071
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4072 non-null   object
 1   open_time                4072 non-null   int64
 2   ticker                   4072 non-null   object
 3   open                     4072 non-null   float64
 4   high                     4072 non-null   float64
 5   low                      4072 non-null   float64
 6   close                    4072 non-null   float64
 7   adj_close                4072 non-null   float64
 8   volume                   4072 non-null   int64
 9   type                     4072 non-null   object
 10  ema_adj_close_200p       3873 non-null   float32
 11  ema_adj_close_200p_diff  3873 non-null   float32
 12  ema_close_200p           3873 non-null   float32
 13  ema_close_200p_diff      3873 non-null   float32
 14  rsi                      3273 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 413.7+ KB
Ticker: RCSL3.SA - Shape (5853, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5853 entries, 0 to 5852
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5853 non-null   object
 1   open_time                5853 non-null   int64
 2   ticker                   5853 non-null   object
 3   open                     5853 non-null   float64
 4   high                     5853 non-null   float64
 5   low                      5853 non-null   float64
 6   close                    5853 non-null   float64
 7   adj_close                5853 non-null   float64
 8   volume                   5853 non-null   int64
 9   type                     5853 non-null   object
 10  ema_adj_close_200p       5654 non-null   float32
 11  ema_adj_close_200p_diff  5654 non-null   float32
 12  ema_close_200p           5654 non-null   float32
 13  ema_close_200p_diff      5654 non-null   float32
 14  rsi                      5839 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 594.6+ KB
Ticker: RAIL3.SA - Shape (2155, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2155 non-null   object
 1   open_time                2155 non-null   int64
 2   ticker                   2155 non-null   object
 3   open                     2155 non-null   float64
 4   high                     2155 non-null   float64
 5   low                      2155 non-null   float64
 6   close                    2155 non-null   float64
 7   adj_close                2155 non-null   float64
 8   volume                   2155 non-null   int64
 9   type                     2155 non-null   object
 10  ema_adj_close_200p       1956 non-null   float32
 11  ema_adj_close_200p_diff  1956 non-null   float32
 12  ema_close_200p           1956 non-null   float32
 13  ema_close_200p_diff      1956 non-null   float32
 14  rsi                      2141 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 219.0+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
Ticker: PNCR11.SA - Shape (115, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              115 non-null    object
 1   open_time                115 non-null    int64
 2   ticker                   115 non-null    object
 3   open                     115 non-null    float64
 4   high                     115 non-null    float64
 5   low                      115 non-null    float64
 6   close                    115 non-null    float64
 7   adj_close                115 non-null    float64
 8   volume                   115 non-null    int64
 9   type                     115 non-null    object
 10  ema_adj_close_200p       0 non-null      object
 11  ema_adj_close_200p_diff  0 non-null      object
 12  ema_close_200p           0 non-null      object
 13  ema_close_200p_diff      0 non-null      object
 14  rsi                      101 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 13.6+ KB
Ticker: BALM4.SA - Shape (4164, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4164 entries, 0 to 4163
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4164 non-null   object
 1   open_time                4164 non-null   int64
 2   ticker                   4164 non-null   object
 3   open                     4164 non-null   float64
 4   high                     4164 non-null   float64
 5   low                      4164 non-null   float64
 6   close                    4164 non-null   float64
 7   adj_close                4164 non-null   float64
 8   volume                   4164 non-null   int64
 9   type                     4164 non-null   object
 10  ema_adj_close_200p       3965 non-null   float32
 11  ema_adj_close_200p_diff  3965 non-null   float32
 12  ema_close_200p           3965 non-null   float32
 13  ema_close_200p_diff      3965 non-null   float32
 14  rsi                      3865 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 423.0+ KB
Ticker: MXRF11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: MGCR11.SA - Shape (410, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              410 non-null    object
 1   open_time                410 non-null    int64
 2   ticker                   410 non-null    object
 3   open                     410 non-null    float64
 4   high                     410 non-null    float64
 5   low                      410 non-null    float64
 6   close                    410 non-null    float64
 7   adj_close                410 non-null    float64
 8   volume                   410 non-null    int64
 9   type                     410 non-null    object
 10  ema_adj_close_200p       211 non-null    float32
 11  ema_adj_close_200p_diff  211 non-null    float32
 12  ema_close_200p           211 non-null    float32
 13  ema_close_200p_diff      211 non-null    float32
 14  rsi                      396 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 41.8+ KB
Ticker: QAGR11.SA - Shape (987, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              987 non-null    object
 1   open_time                987 non-null    int64
 2   ticker                   987 non-null    object
 3   open                     987 non-null    float64
 4   high                     987 non-null    float64
 5   low                      987 non-null    float64
 6   close                    987 non-null    float64
 7   adj_close                987 non-null    float64
 8   volume                   987 non-null    int64
 9   type                     987 non-null    object
 10  ema_adj_close_200p       788 non-null    float32
 11  ema_adj_close_200p_diff  788 non-null    float32
 12  ema_close_200p           788 non-null    float32
 13  ema_close_200p_diff      788 non-null    float32
 14  rsi                      973 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 100.4+ KB
Ticker: LLAO11.SA - Shape (249, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              249 non-null    object
 1   open_time                249 non-null    int64
 2   ticker                   249 non-null    object
 3   open                     249 non-null    float64
 4   high                     249 non-null    float64
 5   low                      249 non-null    float64
 6   close                    249 non-null    float64
 7   adj_close                249 non-null    float64
 8   volume                   249 non-null    int64
 9   type                     249 non-null    object
 10  ema_adj_close_200p       50 non-null     float32
 11  ema_adj_close_200p_diff  50 non-null     float32
 12  ema_close_200p           50 non-null     float32
 13  ema_close_200p_diff      50 non-null     float32
 14  rsi                      129 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 25.4+ KB
Ticker: TKNO3.SA - Shape (5907, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5907 entries, 0 to 5906
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              5907 non-null   object
 1   open_time                5907 non-null   int64
 2   ticker                   5907 non-null   object
 3   open                     5907 non-null   float64
 4   high                     5907 non-null   float64
 5   low                      5907 non-null   float64
 6   close                    5907 non-null   float64
 7   adj_close                5907 non-null   float64
 8   volume                   5907 non-null   int64
 9   type                     5907 non-null   object
 10  ema_adj_close_200p       5708 non-null   float32
 11  ema_adj_close_200p_diff  5708 non-null   float32
 12  ema_close_200p           5708 non-null   float32
 13  ema_close_200p_diff      5708 non-null   float32
 14  rsi                      3989 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 600.1+ KB
Ticker: FLMA11.SA - Shape (2319, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              2319 non-null   object
 1   open_time                2319 non-null   int64
 2   ticker                   2319 non-null   object
 3   open                     2319 non-null   float64
 4   high                     2319 non-null   float64
 5   low                      2319 non-null   float64
 6   close                    2319 non-null   float64
 7   adj_close                2319 non-null   float64
 8   volume                   2319 non-null   int64
 9   type                     2319 non-null   object
 10  ema_adj_close_200p       2120 non-null   float32
 11  ema_adj_close_200p_diff  2120 non-null   float32
 12  ema_close_200p           2120 non-null   float32
 13  ema_close_200p_diff      2120 non-null   float32
 14  rsi                      2305 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 235.7+ KB
Ticker: HPDP11.SA - Shape (940, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              940 non-null    object
 1   open_time                940 non-null    int64
 2   ticker                   940 non-null    object
 3   open                     940 non-null    float64
 4   high                     940 non-null    float64
 5   low                      940 non-null    float64
 6   close                    940 non-null    float64
 7   adj_close                940 non-null    float64
 8   volume                   940 non-null    int64
 9   type                     940 non-null    object
 10  ema_adj_close_200p       741 non-null    float32
 11  ema_adj_close_200p_diff  741 non-null    float32
 12  ema_close_200p           741 non-null    float32
 13  ema_close_200p_diff      741 non-null    float32
 14  rsi                      926 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 95.6+ KB
Ticker: CEDO4.SA - Shape (3950, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3950 entries, 0 to 3949
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              3950 non-null   object
 1   open_time                3950 non-null   int64
 2   ticker                   3950 non-null   object
 3   open                     3950 non-null   float64
 4   high                     3950 non-null   float64
 5   low                      3950 non-null   float64
 6   close                    3950 non-null   float64
 7   adj_close                3950 non-null   float64
 8   volume                   3950 non-null   int64
 9   type                     3950 non-null   object
 10  ema_adj_close_200p       3751 non-null   float32
 11  ema_adj_close_200p_diff  3751 non-null   float32
 12  ema_close_200p           3751 non-null   float32
 13  ema_close_200p_diff      3751 non-null   float32
 14  rsi                      3936 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 401.3+ KB
Ticker: DASA3.SA - Shape (4734, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4734 entries, 0 to 4733
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              4734 non-null   object
 1   open_time                4734 non-null   int64
 2   ticker                   4734 non-null   object
 3   open                     4734 non-null   float64
 4   high                     4734 non-null   float64
 5   low                      4734 non-null   float64
 6   close                    4734 non-null   float64
 7   adj_close                4734 non-null   float64
 8   volume                   4734 non-null   int64
 9   type                     4734 non-null   object
 10  ema_adj_close_200p       4535 non-null   float32
 11  ema_adj_close_200p_diff  4535 non-null   float32
 12  ema_close_200p           4535 non-null   float32
 13  ema_close_200p_diff      4535 non-null   float32
 14  rsi                      4720 non-null   float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 480.9+ KB
Ticker: SHOP11.SA - Shape (229, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              229 non-null    object
 1   open_time                229 non-null    int64
 2   ticker                   229 non-null    object
 3   open                     229 non-null    float64
 4   high                     229 non-null    float64
 5   low                      229 non-null    float64
 6   close                    229 non-null    float64
 7   adj_close                229 non-null    float64
 8   volume                   229 non-null    int64
 9   type                     229 non-null    object
 10  ema_adj_close_200p       30 non-null     float32
 11  ema_adj_close_200p_diff  30 non-null     float32
 12  ema_close_200p           30 non-null     float32
 13  ema_close_200p_diff      30 non-null     float32
 14  rsi                      215 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 23.4+ KB
Ticker: HBRH11.SA - Shape (869, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 869 entries, 0 to 868
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              869 non-null    object
 1   open_time                869 non-null    int64
 2   ticker                   869 non-null    object
 3   open                     869 non-null    float64
 4   high                     869 non-null    float64
 5   low                      869 non-null    float64
 6   close                    869 non-null    float64
 7   adj_close                869 non-null    float64
 8   volume                   869 non-null    int64
 9   type                     869 non-null    object
 10  ema_adj_close_200p       670 non-null    float32
 11  ema_adj_close_200p_diff  670 non-null    float32
 12  ema_close_200p           670 non-null    float32
 13  ema_close_200p_diff      670 non-null    float32
 14  rsi                      855 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 88.4+ KB
Ticker: LAVV3.SA - Shape (805, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805 entries, 0 to 804
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              805 non-null    object
 1   open_time                805 non-null    int64
 2   ticker                   805 non-null    object
 3   open                     805 non-null    float64
 4   high                     805 non-null    float64
 5   low                      805 non-null    float64
 6   close                    805 non-null    float64
 7   adj_close                805 non-null    float64
 8   volume                   805 non-null    int64
 9   type                     805 non-null    object
 10  ema_adj_close_200p       606 non-null    float32
 11  ema_adj_close_200p_diff  606 non-null    float32
 12  ema_close_200p           606 non-null    float32
 13  ema_close_200p_diff      606 non-null    float32
 14  rsi                      791 non-null    float64
dtypes: float32(4), float64(6), int64(2), object(3)
memory usage: 81.9+ KB
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
calc_ema_periods: N√£o foi encontrado registros no per√≠odo informado: 200
index 14 is out of bounds for axis 0 with size 1
Ticker: TJKB11.SA - Shape (1, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s_open_time              1 non-null      object
 1   open_time                1 non-null      int64
 2   ticker                   1 non-null      object
 3   open                     1 non-null      float64
 4   high                     1 non-null      float64
 5   low                      1 non-null      float64

/home/marcelo/des/xpe_projeto_aplicado/src/utils.py:127: RuntimeWarning: Mean of empty slice.
  a[n] = x[1: n + 1].mean()
/home/marcelo/des/xpe_projeto_aplicado/.env/lib64/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)